### ISSUE TITLE
Please upgrade OneSignal Android SDK to latest to fix this crash

### ISSUE THREAD

**Issue by anderscheow** [OneSignal/OneSignal-Flutter-SDK#104]
This crash has been fixed on the OneSignal Android SDK, but flutter version still using older version.

```
java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.anders.jominvites.stg-CqPelc85kePAsUR_WQYIUQ==/base.apk!classes2.dex)
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
        at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:68)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3515)
        at android.app.ActivityThread.access$1300(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
``` 

https://github.com/OneSignal/OneSignal-Android-SDK/issues/754

**Comment by anderscheow** [comment]
#https://github.com/OneSignal/OneSignal-Android-SDK/issues/754

**Comment by anderscheow** [comment]
#102

**Comment by rgomezp** [comment]
Please follow our issue template. This seems related to dependency version conflicts
