### ISSUE TITLE
Android application crash on first launch

### ISSUE THREAD

**Issue by anderscheow** [OneSignal/OneSignal-Flutter-SDK#116]
**Description:**

Whenever fresh install application on a phone, it crashed on first launch. Once I relaunch the app, the issue went away.

**Environment**

1. OneSignal Flutter SDK version: 2.0.1

**Steps to Reproduce Issue:**

1. Add OneSignal to pubspec (assumed fully implemented according to guideline)
2. Build and run the app
3. Boom! Crash on first launch.

**Anything else:**

```java
java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.anders.jominvites.stg-CqPelc85kePAsUR_WQYIUQ==/base.apk!classes2.dex)
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
        at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:68)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3515)
        at android.app.ActivityThread.access$1300(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by jkasten2** [comment]
@anderscheow Can you double check you have this added correct to the very top of your `app/build.gradle` [pre step 4 in the OneSignal setup instructions](https://documentation.onesignal.com/docs/flutter-sdk-setup#section-4-add-the-onesignal-gradle-plugin-android-)?
```gradle
buildscript {
    repositories {
        // ...
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
    }
    dependencies {
        // ...
        // OneSignal-Gradle-Plugin
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.3, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
````

The OneSignal-Gradle-Plugin fixes any version mismatches between firebase versions which is the cause of the crash you are seeing.

**Comment by anderscheow** [comment]
Thanks @jkasten2, this does solve the problem.

**Comment by jkasten2** [comment]
@anderscheow Good to hear!, thanks for letting us know

**Comment by Galahand** [comment]
I'm having a very similar issue, i have the the onesignal gradle plugin configured but it is still crashing with this error in the first run.

`java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in base.apk)
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3737)
        at android.app.ActivityThread.access$1400(ActivityThread.java:236)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1800)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7037)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)`
