### ISSUE TITLE
No implementation found for method OneSignal#presentSettings on channel OneSignal

### ISSUE THREAD

**Issue by chrispypatt** [OneSignal/OneSignal-Flutter-SDK#129]
**Description:**

When trying to present settings using `OneSignal.shared.presentApplicationSettings(); ` the flutter app responds saying the channel does not exist. I have looked in the ios channel code and it does not seem like this is actually in the native code to handle the method channel. 

**Environment**

Flutter SDK: v1.7.8+hotfix.4
Onesignal Flutter SDK : 2.0.2
Added to project using: pub

**Steps to Reproduce Issue:**

1. nstall the OneSignal Flutter SDK using pub into your project (onesignal_flutter: ^2.0.2)
2. Initialize the SDK using OneSignal.shared.init(your_app_id)
3. call OneSignal.shared.presentApplicationSettings(); 
4. see error that channel presentSettings not found

**Anything else:**

<pre>E/flutter (  742): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#presentSettings on channel OneSignal)
E/flutter (  742): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter (  742): <asynchronous suspension>
E/flutter (  742): #1      OneSignal.presentApplicationSettings (package:onesignal_flutter/onesignal_flutter.dart:151:20)
E/flutter (  742): <asynchronous suspension>
E/flutter (  742): #2      _AccountPageWidgetState._toggleNotifications (package:savour_deals_flutter/pages/tabPages/accountTabPage.dart:239:17)
E/flutter (  742): <asynchronous suspension>
E/flutter (  742): #3      _AccountPageWidgetState.build.<anonymous closure> (package:savour_deals_flutter/pages/tabPages/accountTabPage.dart:163:30)
E/flutter (  742): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter (  742): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter (  742): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (  742): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (  742): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
E/flutter (  742): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (  742): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (  742): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (  742): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (  742): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (  742): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (  742): #15     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (  742): #16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (  742): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (  742): #18     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter (  742): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)</pre>

**Comment by rgomezp** [comment]
I was able to repoduce:
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#initInAppMessageClickedHandlerParams on channel OneSignal)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      OneSignal.setInAppMessageClickedHandler (package:onesignal_flutter/onesignal_flutter.dart:110:14)
#2      _MyAppState.initPlatformState (package:onesignal_example/main.dart:58:6)
#3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#4      _MyAppState.initPlatformState (package:onesignal_example/main.dart:30:33)
#5      _MyAppState.initState (package:onesignal_example/main.dart:26:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
#10     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:939:16)
#11     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:910:5)
#12     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:856:17)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
#14     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:855:13)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
#16     runApp (package:flutter/src/widgets/binding.dart:786:7)
#17     main (package:onesignal_example/main.dart:7:16)
#18     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:216:25)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1500:12)
#23     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:208:5)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#presentSettings on channel OneSignal)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      OneSignal.presentApplicationSettings (package:onesignal_flutter/onesignal_flutter.dart:151:20)
<asynchronous suspension>
#2      _MyAppState.initPlatformState (package:onesignal_example/main.dart:83:22)
<asynchronous suspension>
#3      _MyAppState.initState (package:onesignal_example/main.dart:26:5)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
#8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:939:16)
#9      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:910:5)
#10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:856:17)
#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
#12     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:855:13)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
#14     runApp (package:flutter/src/widgets/binding.dart:786:7)
#15     main (package:onesignal_example/main.dart:7:16)
#16     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:216:25)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1500:12)
#21     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:208:5)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#addTrigger on channel OneSignal)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      OneSignal.addTrigger (package:onesignal_flutter/onesignal_flutter.dart:291:27)
<asynchronous suspension>
#2      _MyAppState.oneSignalInAppMessagingTriggerExamples (package:onesignal_example/main.dart:242:22)
<asynchronous suspension>
#3      _MyAppState.initPlatformState (package:onesignal_example/main.dart:95:5)
<asynchronous suspension>
#4      _MyAppState.initState (package:onesignal_example/main.dart:26:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
#9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:939:16)
#10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:910:5)
#11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:856:17)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
#13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:855:13)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
#15     runApp (package:flutter/src/widgets/binding.dart:786:7)
#16     main (package:onesignal_example/main.dart:7:16)
#17     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:216:25)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1500:12)
#22     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:208:5)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#addTriggers on channel OneSignal)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      OneSignal.addTriggers (package:onesignal_flutter/onesignal_flutter.dart:297:27)
<asynchronous suspension>
#2      _MyAppState.oneSignalInAppMessagingTriggerExamples (package:onesignal_example/main.dart:250:22)
#3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#4      _MyAppState.oneSignalInAppMessagingTriggerExamples (package:onesignal_example/main.dart:238:41)
#5      _MyAppState.initPlatformState (package:onesignal_example/main.dart:95:5)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#16     OneSignal.requiresUserPrivacyConsent (package:onesignal_flutter/onesignal_flutter.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#23     Future._complete (dart:async/future_impl.dart:473:7)
#24     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#25     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#26     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#27     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
#28     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#34     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#35     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#39     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#removeTriggerForKey on channel OneSignal)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      OneSignal.removeTriggerForKey (package:onesignal_flutter/onesignal_flutter.dart:303:27)
<asynchronous suspension>
#2      _MyAppState.oneSignalInAppMessagingTriggerExamples (package:onesignal_example/main.dart:254:22)
#3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#4      _MyAppState.oneSignalInAppMessagingTriggerExamples (package:onesignal_example/main.dart:238:41)
#5      _MyAppState.initPlatformState (package:onesignal_example/main.dart:95:5)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#16     OneSignal.requiresUserPrivacyConsent (package:onesignal_flutter/onesignal_flutter.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#23     Future._complete (dart:async/future_impl.dart:473:7)
#24     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#25     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#26     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#27     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
#28     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#34     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#35     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#39     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#getTriggerValueForKey on channel OneSignal)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      OneSignal.getTriggerValueForKey (package:onesignal_flutter/onesignal_flutter.dart:314:27)
<asynchronous suspension>
#2      _MyAppState.oneSignalInAppMessagingTriggerExamples (package:onesignal_example/main.dart:257:50)
#3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#4      _MyAppState.oneSignalInAppMessagingTriggerExamples (package:onesignal_example/main.dart:238:41)
#5      _MyAppState.initPlatformState (package:onesignal_example/main.dart:95:5)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#16     OneSignal.requiresUserPrivacyConsent (package:onesignal_flutter/onesignal_flutter.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#23     Future._complete (dart:async/future_impl.dart:473:7)
#24     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#25     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#26     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#27     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
#28     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#34     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#35     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#39     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

Thanks for your patience while we resolve.

**Comment by chrispypatt** [comment]
Quick question with fallbackToSettings, will this be affected by the iOS issue of     OneSignal.shared.promptLocationPermission() not completing? Or would settings still open even though promptLocationPermission() does not complete?

**Comment by rgomezp** [comment]
Howdy @chrispratt,
Sorry for the delayed response. I'm not aware of these being related in any way so I don't believe there to be any side-effects

**Comment by davidAg9** [comment]
hello has this issue been solved
can't seem to find any solution online
