### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException java.lang.IllegalThreadStateException

### ISSUE THREAD

**Issue by JCKodel** [OneSignal/OneSignal-Flutter-SDK#189]
**Description:**

Crashlytics
OneSignalPrefs.java line 117
com.onesignal.OneSignalPrefs$WritePrefHandlerThread.startDelayedWrite

This issue has 72 crashes affecting 72 users
Last 7 days

**Environment**

onesignal_flutter: ^2.3.1

**Steps to Reproduce Issue:**

1. Don't know (bug reported in Crashlytics on production)

**Anything else:**

(crash stacktraces, as well as any other information here)
```
Fatal Exception: java.lang.RuntimeException
java.lang.IllegalThreadStateException

OneSignalPrefs.java line 117
com.onesignal.OneSignalPrefs$WritePrefHandlerThread.startDelayedWrite

Fatal Exception: java.lang.RuntimeException: java.lang.IllegalThreadStateException
       at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7091)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

Caused by java.lang.IllegalThreadStateException
       at java.lang.Thread.start(Thread.java:724)
       at com.onesignal.OneSignalPrefs$WritePrefHandlerThread.startDelayedWrite(OneSignalPrefs.java:117)
       at com.onesignal.OneSignalPrefs.startDelayedWrite(OneSignalPrefs.java:183)
       at com.onesignal.OneSignal.setAppContext(OneSignal.java:601)
       at com.onesignal.OneSignalSyncServiceUtils.doBackgroundSync(OneSignalSyncServiceUtils.java:175)
       at com.onesignal.SyncJobService.onStartJob(SyncJobService.java:40)
       at android.app.job.JobService$1.onStartJob(JobService.java:62)
       at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7091)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```
![image](https://user-images.githubusercontent.com/379339/71422845-c069d300-2663-11ea-986c-86f70347effe.png)

**Comment by jkasten2** [comment]
Thanks for reporting. This looks to be the same as the following issue in the native OneSignal-Android-SDK.
https://github.com/OneSignal/OneSignal-Android-SDK/issues/917

**Comment by rgomezp** [comment]
Let's follow the issue in the native repository. Cheers
