### ISSUE TITLE
OneSignal throws Exception on Android

### ISSUE THREAD

**Issue by DRSchlaubi** [OneSignal/OneSignal-Flutter-SDK#209]
**Description:**
OneSignal throws the Exception below

(your description here)

**Environment**
Android: 10
OneSignal: 2.3.3
Flutter: v1.12.13+hotfix.8

```W/System.err( 3699): java.lang.InterruptedException
W/System.err( 3699): 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1244)
W/System.err( 3699): 	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:336)
W/System.err( 3699): 	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:384)
W/System.err( 3699): 	at com.onesignal.OneSignalSyncServiceUtils$SyncRunnable.run(OneSignalSyncServiceUtils.java:236)
```

**Comment by jkasten2** [comment]
@DRSchlaubi Can you include the exception itself above this stacktrace?
Also if you have steps on reproducing the issue. Thanks.

**Comment by DRSchlaubi** [comment]
I don't have it anymore but it was a interrupted exception
