### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "OneSignal":

### ISSUE THREAD

**Issue by brux88** [OneSignal/OneSignal-Flutter-SDK#236]
**Description:**
i am using codemagic for CI, without oneisgnal everything works, as soon as i insert in my project flutter onesignal codemagic it gives me this error:

```
 Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.onesignal.example for device (ios)...

Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.

Running pod install...                                          
    2.2s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
      Using `ARCHS` setting to build architectures of target `Pods-OneSignalNotificationServiceExtension`: (``)

    Finding Podfile changes
      - Flutter
      - OneSignal
      - onesignal_flutter

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `onesignal_flutter` from `.symlinks/plugins/onesignal_flutter/ios`

    Resolving dependencies of `Podfile`

    Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
      CDN: trunk Relative path downloaded: CocoaPods-version.yml, save ETag: "04c48efc0cce3f97c1ebf74b677935d8-ssl-df"
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "OneSignal":
      In snapshot (Podfile.lock):
        OneSignal (< 3.0, = 2.13.1, >= 2.9.4)

      In Podfile:
        OneSignal (< 3.0, >= 2.9.4)

        onesignal_flutter (from `.symlinks/plugins/onesignal_flutter/ios`) was resolved to 2.4.0, which depends on
          OneSignal (= 2.13.1)


    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * changed the constraints of dependency `OneSignal` inside your development pod `onesignal_flutter`.
       You should run `pod update OneSignal` to apply changes you've made.

    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
    /Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
    /Users/builder/.rbenv/versions/2.6.5/bin/pod:23:in `load'
    /Users/builder/.rbenv/versions/2.6.5/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

    [!] Automatically assigning platform `iOS` with version `10.0` on target `OneSignalNotificationServiceExtension` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

Error running pod install




Build failed :|
Failed to build for iOS
```

**Environment**

Flutter : 1.12.13+hotfix.8
i try with 
  onesignal_flutter: ^2.2.0
and 
 onesignal_flutter: ^2.4.0

**Steps to Reproduce Issue:**

1. I downloaded your sample project
2. I uploaded it to codemagic
3.i buyild and show me error

**Comment by ercadev** [comment]
Have you tried to upgrade your pods?

**Comment by brux88** [comment]
YES, but not work

**Comment by ercadev** [comment]
@brux88 okay, I think I had the same problem but upgraded pods solved it for me. Did you remove the podfile.lock before running `pod update` ?

**Comment by brux88** [comment]
yes but the same problem

**Comment by mma-amini** [comment]
problem

**Comment by mma-amini** [comment]
I have this problem too.

**Comment by mma-amini** [comment]
Solved this way:
run `pod update OneSignal`
run 'pod install'

**Comment by rymesaint** [comment]
i'v got the solution from react-native one, like this :
run **pod repo update** 
then try to update pod if available 
run **pod install**

**Comment by rgomezp** [comment]
Thanks for providing the solution!
