### ISSUE TITLE
Crash in Android application 

### ISSUE THREAD

**Issue by iamatulkumar** [OneSignal/OneSignal-Flutter-SDK#246]
<img width="1257" alt="Screenshot 2020-05-21 at 4 51 00 PM" src="https://user-images.githubusercontent.com/20879070/82555808-1d6fa380-9b86-11ea-9523-e32ff7255deb.png">

**Description:**
Android application crash in production 

(your description here)

**Environment**

Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.XXXX/com.XXXXX.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'boolean com.onesignal.f1$u.d' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4322)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4354)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

Caused by java.lang.NullPointerException: Attempt to read from field 'boolean com.onesignal.f1$u.d' on a null object reference
       at com.onesignal.f1.c0(:7)
       at com.onesignal.f1.e0(:17)
       at com.onesignal.f1.m(:24)
       at com.onesignal.f1.R(:12)
       at com.onesignal.a.a(:27)
       at com.onesignal.a.d(:6)
       at com.onesignal.b.onActivityResumed()
       at android.app.Application.dispatchActivityResumed(Application.java:470)
       at android.app.Activity.dispatchActivityResumed(Activity.java:1265)
       at android.app.Activity.onResume(Activity.java:1789)
       at h.c.b.a.onResume()
       at com.anggach.flutterbranchioplugin.src.b.onResume()
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1560)
       at android.app.Activity.performResume(Activity.java:7952)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4312)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4354)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by right7ctrl** [comment]
Same here

**Comment by rgomezp** [comment]
Howdy,
Thank you for the details and for your patience. Can you please provide us with reproduction steps?

**Comment by rgomezp** [comment]
Closing due to no response.
