### ISSUE TITLE
Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.FirebaseMessagingService>

### ISSUE THREAD

**Issue by figengungor** [OneSignal/OneSignal-Flutter-SDK#261]
**Description:**

The app crashes with the following error logs when run very first time. The example app is working fine but in my project I have `firebase_admob` and `firebase_analytics` along with `onesignal_flutter`. I suspect it's onesignal gradle plugin that is not working as intended and does not resolve conflicts because after checking  some issues out I ended up adding `implementation 'com.google.firebase:firebase-messaging:20.2.1'` into app/build.gardle dependencies block and it fixed the first time launch crash issue.

I spent some time searching this so please either fix onesignal gradle plugin or mention about adding extra implementation into readmes.

Here are the logs:

```
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Lost connection to device.
D/FA      (22289): Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=347, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-6782954986992636137}]
I/zygote64(22289): Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.FirebaseMessagingService>: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.afy.resto-zT4KlGX_W45jHudojpNciQ==/base.apk:classes3.dex)
I/zygote64(22289):   at java.lang.Class java.lang.VMClassLoader.findLoadedClass(java.lang.ClassLoader, java.lang.String) (VMClassLoader.java:-2)
I/zygote64(22289):   at java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) (ClassLoader.java:738)
I/zygote64(22289):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:363)
I/zygote64(22289):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote64(22289):   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3456)
I/zygote64(22289):   at void android.app.ActivityThread.-wrap4(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
I/zygote64(22289):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1702)
I/zygote64(22289):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/zygote64(22289):   at void android.os.Looper.loop() (Looper.java:164)
I/zygote64(22289):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6710)
I/zygote64(22289):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(22289):   at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
I/zygote64(22289):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:770)
I/zygote64(22289): 
D/AndroidRuntime(22289): Shutting down VM
E/AndroidRuntime(22289): FATAL EXCEPTION: main
E/AndroidRuntime(22289): Process: com.afy.resto, PID: 22289
E/AndroidRuntime(22289): java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.afy.resto-zT4KlGX_W45jHudojpNciQ==/base.apk:classes3.dex)
E/AndroidRuntime(22289): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime(22289): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime(22289): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime(22289): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(22289): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3456)
E/AndroidRuntime(22289): 	at android.app.ActivityThread.-wrap4(Unknown Source:0)
E/AndroidRuntime(22289): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1702)
E/AndroidRuntime(22289): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(22289): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(22289): 	at android.app.ActivityThread.main(ActivityThread.java:6710)
E/AndroidRuntime(22289): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22289): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime(22289): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
I/Process (22289): Sending signal. PID: 22289 SIG: 9
```

**Environment**

**Steps to Reproduce Issue:**

1. Add firebase_admob or firebase_analytics along  with onesignal_flutter into pubspec.yaml 
  onesignal_flutter: ^2.5.0
  firebase_analytics: 5.0.15
  firebase_admob: ^0.9.3+2
2. Add OneSignal Gradle Plugin as suggested [here](https://github.com/OneSignal/OneSignal-Gradle-Plugin) 
classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.8, 0.99.99]'
3. Run project very first time and see the error logs

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Howdy,
Thank you for your patience.

Can you please include your entire gradle file? Thank you.

**Comment by rgomezp** [comment]
Closing due to no response.
