### ISSUE TITLE
setExternalUserId crashes with ClassNotFoundException looking for OSExternalUserIdUpdateCompletionHandler

### ISSUE THREAD

**Issue by DarthCoder117** [OneSignal/OneSignal-Flutter-SDK#272]
**Description:**

Installing the OneSignal SDK for Flutter using the SDK setup guide, and attempt to set an external user ID results in the application crashing with a ClassNotFoundException.

**Environment**

1. pub `onesignal_flutter` version is `^2.0.0`
2. gradle plugin: `classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.8'`
3. app/src/build.gradle dependencies: `implementation 'com.onesignal:OneSignal:3.14.1'`

Also tried `implementation 'com.onesignal:OneSignal:3.8.4'` and other combinations of versions.

**Steps to Reproduce Issue:**

1. Install SDK using [Flutter SDK Setup](https://documentation.onesignal.com/docs/flutter-sdk-setup) guide.
2. Initialize as shown in the guide with `OneSignal.shared.init()`
3. Later on, after logging in the user, call `OneSignal.shared.setExternalUserId(someUserId)`
4. Crash

**Anything else:**

```
E/flutter ( 9561): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/onesignal/OneSignal$OSExternalUserIdUpdateCompletionHandler;
E/flutter ( 9561): 	at com.onesignal.flutter.OneSignalPlugin.registerWith(OneSignalPlugin.java:57)
E/flutter ( 9561): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:33)
E/flutter ( 9561): 	at com.eshuconnect.eshu_connect_guide.MainActivity.onCreate(MainActivity.kt:11)
E/flutter ( 9561): 	at android.app.Activity.performCreate(Activity.java:7802)
E/flutter ( 9561): 	at android.app.Activity.performCreate(Activity.java:7791)
E/flutter ( 9561): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
E/flutter ( 9561): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
E/flutter ( 9561): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
E/flutter ( 9561): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/flutter ( 9561): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/flutter ( 9561): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/flutter ( 9561): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/flutter ( 9561): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/flutter ( 9561): 	at android.os.Looper.loop(Looper.java:214)
E/flutter ( 9561): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/flutter ( 9561): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 9561): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter ( 9561): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 9561): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.OneSignal$OSExternalUserIdUpdateCompletionHandler" on path: DexPathList[[zip file "/data/app/com.eshuconnect.eshu_connect_guide-bcF9PAaamBn07Ds4E6Fhqg==/base.apk"],nativeLibraryDirectories=[/data/app/com.eshuconnect.eshu_connect_guide-bcF9PAaamBn07Ds4E6Fhqg==/lib/x86, /data/app/com.eshuconnect.eshu_connect_guide-bcF9PAaamBn07Ds4E6Fhqg==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
```

**Comment by DarthCoder117** [comment]
Nvm. Odd behavior in another library caused the app to close and reopen and then the OneSignal init wasn't done.
