### ISSUE TITLE
MissingPluginException when shipping through google play store

### ISSUE THREAD

**Issue by trezm** [OneSignal/OneSignal-Flutter-SDK#299]
**Description:**

I am now getting a MissingPluginException when shipping through the play store. If I run via `flutter run -d all` with an attached device, I do not get any errors. Here is the exception:

**Environment**

* One Signal Flutter version 2.6.1

```
Flutter 1.21.0-9.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 81a45ec2e5 (2 weeks ago) • 2020-08-27 14:14:33 -0700
Engine • revision 20a9531835
Tools • Dart 2.10.0 (build 2.10.0-7.3.beta)
```

**Steps to Reproduce Issue:**

1. build app via `flutter build appbundle`
1. release through the play store
1. call `OneSignal.shared.getPermissionSubscriptionState()`

**Anything else:**

```
09-11 12:29:18.372 22654 22922 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#getPermissionSubscriptionState on channel OneSignal)
09-11 12:29:18.372 22654 22922 E flutter : #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
09-11 12:29:18.372 22654 22922 E flutter : <asynchronous suspension>
09-11 12:29:18.372 22654 22922 E flutter : #1      OneSignal.getPermissionSubscriptionState (package:onesignal_flutter/onesignal_flutter.dart:219)
09-11 12:29:18.372 22654 22922 E flutter : <asynchronous suspension>
09-11 12:29:18.372 22654 22922 E flutter : #2      SessionGRPCBloc.createNewSession (package:droppod/bloc/session_grpc_bloc.dart:113)
09-11 12:29:18.372 22654 22922 E flutter : <asynchronous suspension>
09-11 12:29:18.372 22654 22922 E flutter : #3      _SignInState.build.<anonymous closure> (package:droppod/widgets/sign_in.dart:63)
09-11 12:29:18.372 22654 22922 E flutter : <asynchronous suspension>
09-11 12:29:18.372 22654 22922 E flutter : 
```

**Comment by trezm** [comment]
Looks to be related to this: https://github.com/flutter/flutter/issues/58113

**Comment by nan-li** [comment]
Hi @trezm,

I apologize for the very late response. Was this ever resolved for you?

**Comment by trezm** [comment]
Unfortunately we had to switch to a different provider as we could not resolve the issue. I haven't checked in the last two years so it's hard to say if it was resolved, feel free to close the issue though.
