### ISSUE TITLE
Unable to start receiver com.onesignal.GcmBroadcastReceiver

### ISSUE THREAD

**Issue by vernalclareai** [OneSignal/OneSignal-Flutter-SDK#300]
**Description:**

Hi, I am getting the crash report from the Firebase Crash Analytics for my android app.
Here is crash report from Firebase.

- - -
Fatal Exception: java.lang.RuntimeException
Unable to start receiver com.onesignal.GcmBroadcastReceiver: java.lang.RuntimeException: bad array lengths

- - -
android.app.ActivityThread.handleReceiver
Caused by java.lang.RuntimeException
bad array lengths

- - -
android.os.Parcel.readIntArray (Parcel.java:988)

## androidx.core.app.l.a

com.onesignal.OneSignalNotificationManager.assignGrouplessNotifications
com.onesignal.GenerateNotification.showNotification
com.onesignal.GenerateNotification.fromJsonPayload
com.onesignal.NotificationBundleProcessor.ProcessJobForDisplay
com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService
com.onesignal.GcmBroadcastReceiver.startGCMService
com.onesignal.GcmBroadcastReceiver.processOrderBroadcast
com.onesignal.GcmBroadcastReceiver.onReceive
android.app.ActivityThread.handleReceiver (ActivityThread.java:3306)

**Environment**
onesignal_flutter 2.6.1

**Steps to Reproduce Issue:**

1.   Install the OneSignal Flutter SDK using pub into your project
1.  Initialize the SDK using OneSignal.shared.init(your_app_id)
1.  Receiving notification is okay, but getting the crash from Play Store Users via Firebase.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by vernalclareai** [comment]
HI, anyone can help on it?
thanks.

**Comment by nan-li** [comment]
Hi @vernalclareai,
I apologize for the very late reply. 

Is this still an active crash for you? If so, can you share how many users are affected, and what Android devices and the Android versions experiencing this crash?

**Comment by MahmmoudSabri** [comment]
I have the same issue, only in android 12 or above devices 

please help 

``` java.lang.RuntimeException: Unable to start receiver com.onesignal.GcmBroadcastReceiver: java.lang.IllegalArgumentException: com.myapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(22706): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(22706): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4480)
E/AndroidRuntime(22706): 	at android.app.ActivityThread.access$1800(ActivityThread.java:277)
E/AndroidRuntime(22706): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2181)
E/AndroidRuntime(22706): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(22706): 	at android.os.Looper.loopOnce(Looper.java:211)
E/AndroidRuntime(22706): 	at android.os.Looper.loop(Looper.java:300)
E/AndroidRuntime(22706): 	at android.app.ActivityThread.main(ActivityThread.java:8282)
E/AndroidRuntime(22706): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22706): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
E/AndroidRuntime(22706): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
E/AndroidRuntime(22706): Caused by: java.lang.IllegalArgumentException: com.myapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(22706): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(22706): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
E/AndroidRuntime(22706): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
E/AndroidRuntime(22706): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
E/AndroidRuntime(22706): 	at com.onesignal.GenerateNotification.getNewActionPendingIntent(GenerateNotification.java:189)
E/AndroidRuntime(22706): 	at com.onesignal.GenerateNotification.createGenericPendingIntentsForNotif(GenerateNotification.java:398)
E/AndroidRuntime(22706): 	at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:382)
E/AndroidRuntime(22706): 	at com.onesignal.GenerateNotification.fromJsonPayload(GenerateNotification.java:110)
E/AndroidRuntime(22706): 	at com.onesignal.NotificationBundleProcessor.ProcessJobForDisplay(NotificationBundleProcessor.java:107)
E/AndroidRuntime(22706): 	at com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService(NotificationBundleProcessor.java:90)
E/AndroidRuntime(22706): 	at com.onesignal.GcmBroadcastReceiver.startGCMService(GcmBroadcastReceiver.java:138)
E/AndroidRuntime(22706): 	at com.onesignal.GcmBroadcastReceiver.processOrderBroadcast(GcmBroadcastReceiver.java:129)
E/AndroidRuntime(22706): 	at com.onesignal.GcmBroadcastReceiver.onReceive(GcmBroadcastReceiver.java:70)
E/AndroidRuntime(22706): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4467)```

**Comment by emawby** [comment]
Closing issue as stale. If this is still happening in 2024 feel free to tag me to reopen
