### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'com.onesignal.OSSubscriptionState

### ISSUE THREAD

**Issue by rafaelviny** [OneSignal/OneSignal-Flutter-SDK#306]
Good Morning

until 2 days ago everything was working correctly, however when generating the version of IOS and working on it, android started to give these errors.

**Description:**

`       ] V/OneSignal(31874): Initializing the OneSignal Flutter SDK (2.2.0)
[        ] E/OneSignal(31874): Cannot change requiresUserPrivacyConsent() from TRUE to FALSE
[        ] V/OneSignal(31874): OneSignal SDK initialization delayed, user privacy consent is set to required for this application.
[  +11 ms] W/OneSignal(31874): Method getPermissionSubscriptionState() was called before the user provided privacy consent. Your application is set to require the user's privacy consent before the OneSignal SDK can be initialized. Please ensure the user has provided consent before calling this method. You can check the latest OneSignal consent status by calling OneSignal.userProvidedPrivacyConsent()
[  +11 ms] E/MethodChannel#OneSignal(31874): Failed to handle method call
[        ] E/MethodChannel#OneSignal(31874): java.lang.NullPointerException: Attempt to invoke virtual method 'com.onesignal.OSSubscriptionState com.onesignal.OSPermissionSubscriptionState.getSubscriptionStatus()' on a null object reference
[        ] E/MethodChannel#OneSignal(31874): 	at com.onesignal.flutter.OneSignalSerializer.convertPermissionSubscriptionStateToMap(OneSignalSerializer.java:47)
[        ] E/MethodChannel#OneSignal(31874): 	at com.onesignal.flutter.OneSignalPlugin.getPermissionSubscriptionState(OneSignalPlugin.java:224)
[        ] E/MethodChannel#OneSignal(31874): 	at com.onesignal.flutter.OneSignalPlugin.onMethodCall(OneSignalPlugin.java:104)
[        ] E/MethodChannel#OneSignal(31874): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
[        ] E/MethodChannel#OneSignal(31874): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[        ] E/MethodChannel#OneSignal(31874): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
[        ] E/MethodChannel#OneSignal(31874): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MethodChannel#OneSignal(31874): 	at android.os.MessageQueue.next(MessageQueue.java:325)
[        ] E/MethodChannel#OneSignal(31874): 	at android.os.Looper.loop(Looper.java:142)
[        ] E/MethodChannel#OneSignal(31874): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
[        ] E/MethodChannel#OneSignal(31874): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#OneSignal(31874): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
[        ] E/MethodChannel#OneSignal(31874): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
`

**Environment**

Flutter 1.17.5
onesignal_flutter: 2.6.1
Windows 10

**source**

![problema](https://user-images.githubusercontent.com/3612516/94937573-bf40be80-049d-11eb-8038-d247aaaf2c6f.PNG)

**Comment by rafaelviny** [comment]
solved add OneSignal.shared.consentGranted(true);

![image](https://user-images.githubusercontent.com/3612516/94976249-5af41e00-04e2-11eb-8410-6346818a0762.png)
