### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by yelkamel** [OneSignal/OneSignal-Flutter-SDK#334]
Hello,

I tried to find a solution but since I added OneSignal in my project, with CrashAnaylitcs, I can see that I got a crash for 300 users:

`Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
       at com.onesignal.flutter.FlutterRegistrarResponder$1.run(FlutterRegistrarResponder.java:26)
       at com.onesignal.flutter.FlutterRegistrarResponder.runOnMainThread(FlutterRegistrarResponder.java:61)
       at com.onesignal.flutter.FlutterRegistrarResponder.replySuccess(FlutterRegistrarResponder.java:23)
       at com.onesignal.flutter.OneSignalPlugin$5.onComplete(OneSignalPlugin.java:310)
       at com.onesignal.OneSignalStateSynchronizer$1$1.run(OneSignalStateSynchronizer.java:230)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6702)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)`

* onesignal_flutter: ^2.6.2

Sadly, I'm not able to reproduce but maybe someone can help me to prevent that for my futur release ? 

Regards,

**Comment by kleberandrade** [comment]
I have the same problem

**Comment by jkasten2** [comment]
@yelkamel @kleberandrade We believe we fixed this in the 3.x.x major release. Can you try upgrading to the latest 3.1.0 version?
There is a migration available which should make the upgrade process easy.
https://documentation.onesignal.com/docs/mobile-2020-api-migration-guide

**Comment by nan-li** [comment]
Since this was fixed in the 3.x.x major release, and there has been no new activity on this issue, I will close it.
