### ISSUE TITLE
not getting notifications in release apk

### ISSUE THREAD

**Issue by darab-singh93** [OneSignal/OneSignal-Flutter-SDK#358]
I am using onesignal_flutter: ^2.6.3
flutter sdk :   1.22.6 stable
not getting notification in released apk.

**Comment by Jeasmine** [comment]
Hey @darab-singh93! is this still happening to you? Can you provide your build.gradle file? Thanks!

**Comment by phucho236** [comment]
> Hey @darab-singh93! is this still happening to you? Can you provide your build.gradle file? Thanks!

i have same issue. this logcat
`2021-05-20 16:48:46.655 31382-31382/? D/OneSignal: onActivityPaused: flu.gonosen.liber_love.MainActivity@bdb7206
2021-05-20 16:48:46.656 31382-31382/? D/OneSignal: curActivity is NOW: null
2021-05-20 16:48:46.697 31382-31382/? D/OneSignal: onActivityStopped: flu.gonosen.liber_love.MainActivity@bdb7206
2021-05-20 16:48:46.699 31382-31382/? D/OneSignal: curActivity is NOW: null
2021-05-20 16:48:48.661 31382-31494/? D/OneSignal: Application lost focus
2021-05-20 16:48:48.665 31382-31494/? D/OneSignal: GMSLocationController onFocusChange!
2021-05-20 16:48:54.120 32591-32644/? I/flutter: on change OneSignalBloc: Change { currentState: OneSignalInitial, nextState: OneSignalLoading }
2021-05-20 16:48:54.146 32591-32591/? V/OneSignal: Initializing the OneSignal Flutter SDK (2.2.0)
2021-05-20 16:48:54.148 32591-32591/? D/OneSignal: OneSignal SessionManager initSessionFromCache
2021-05-20 16:48:54.149 32591-32591/? D/OneSignal: OneSignal InAppMessageTracker initInfluencedTypeFromCache: OSChannelTracker{tag=iam_id, influenceType=UNATTRIBUTED, indirectIds=null, directId='null'}
2021-05-20 16:48:54.149 32591-32591/? D/OneSignal: OneSignal NotificationTracker initInfluencedTypeFromCache: OSChannelTracker{tag=notification_id, influenceType=UNATTRIBUTED, indirectIds=null, directId='null'}
2021-05-20 16:48:54.150 32591-32591/? D/OneSignal: OneSignal getUnattributedUniqueOutcomeEventsSentByChannel: null
2021-05-20 16:48:54.153 32591-32709/? D/OneSignal: redisplayedInAppMessages: []
2021-05-20 16:48:54.154 32591-32709/? D/OneSignal: Attempted to clean 6 month old IAM data, but none exists!
2021-05-20 16:48:54.155 32591-32710/? I/OneSignal: Restoring notifications
2021-05-20 16:48:54.156 32591-32710/? I/OneSignal: Querying DB for notifs to restore: created_time > 1620899334 AND dismissed = 0 AND opened = 0 AND is_summary = 0 AND expire_time > 1621504134
2021-05-20 16:48:54.157 32591-32591/? E/MethodChannel#OneSignal: Failed to handle method call
    java.lang.ClassCastException: c.a.a.a.c.f cannot be cast to c.a.a.a.a
        at com.onesignal.f3.<init>(Unknown Source:62)
        at com.onesignal.a2.S(Unknown Source:9)
        at com.onesignal.a2.a(Unknown Source:110)
        at com.onesignal.flutter.OneSignalPlugin.b(Unknown Source:29)
        at com.onesignal.flutter.OneSignalPlugin.onMethodCall(Unknown Source:10)
        at g.a.c.a.k$a.a(Unknown Source:17)
        at io.flutter.embedding.engine.b.b.a(Unknown Source:57)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-05-20 16:48:54.158 32591-32644/? I/flutter: on change OneSignalBloc: Change { currentState: OneSignalLoading, nextState: one signal error: PlatformException(error, c.a.a.a.c.f cannot be cast to c.a.a.a.a, null, java.lang.ClassCastException: c.a.a.a.c.f cannot be cast to c.a.a.a.a
2021-05-20 16:48:54.158 32591-32644/? I/flutter:     at com.onesignal.flutter.OneSignalPlugin.b(Unknown Source:29)
2021-05-20 16:48:54.158 32591-32644/? I/flutter:     at com.onesignal.flutter.OneSignalPlugin.onMethodCall(Unknown Source:10)
2021-05-20 16:48:56.869 32591-32644/? I/flutter: on change OneSignalBloc: Change { currentState: OneSignalInitial, nextState: OneSignalLoading }
2021-05-20 16:48:56.884 32591-32591/? E/OneSignal: You must initialize OneSignal before modifying tags!Moving this operation to a pending task queue.
2021-05-20 16:48:56.884 32591-32591/? I/OneSignal: Adding a task to the pending queue with ID: 1
2021-05-20 16:48:56.889 32591-32644/? I/flutter: on change OneSignalBloc: Change { currentState: OneSignalLoading, nextState: one signal error: PlatformException(OneSignal, Encountered an error updating tags (-1): You must initialize OneSignal before modifying tags!Moving this operation to a pending task queue., null, null) }
`

**Comment by wahyu-handayani** [comment]
is there any update ? I have the same issue
