### ISSUE TITLE
List of classes of Android One Signal needed for MultiDEX primary DEX file 

### ISSUE THREAD

**Issue by SenChai2047** [OneSignal/OneSignal-Flutter-SDK#366]
**Description:**

Hi I am using onesignal_flutter: ^2.6.2
I encountered a problem on Android as described below (no problem on iOS).
I was adding a lot of functionality not related to OneSignal to my App and needed to enable MultiDEX.
My minSdkVersion was 16, I changed it to 21, then multiDEX was enabled automatically.
Then I encountered these errors (Build succeeded, these errors are run time)

(My Android App and OneSignal was running smoothly before I added additional functionalities that required me to enable MultiDEX. Then I was getting these errors. These are the only errors I got and they are all related to OneSignal.)

```
E/flutter (13418): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#setLogLevel on channel OneSignal)
E/flutter (13418): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (13418): <asynchronous suspension>
E/flutter (13418): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (13418): #2      OneSignal.setLogLevel (package:onesignal_flutter/onesignal_flutter.dart:72:20)
E/flutter (13418): #3      main (package:app/main.dart:18:20)
E/flutter (13418): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (13418): #5      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (13418): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (13418): #7      _runZoned (dart:async/zone.dart:1630:10)
E/flutter (13418): #8      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (13418): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (13418): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (13418): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (13418): 
E/flutter (13418): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#log on channel OneSignal)
E/flutter (13418): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (13418): <asynchronous suspension>
E/flutter (13418): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (13418): #2      OneSignal._onesignalLog (package:onesignal_flutter/onesignal_flutter.dart:391:20)
E/flutter (13418): #3      OneSignal.init (package:onesignal_flutter/onesignal_flutter.dart:59:5)
E/flutter (13418): #4      main (package:app/main.dart:20:20)
E/flutter (13418): #5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (13418): #6      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (13418): #7      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (13418): #8      _runZoned (dart:async/zone.dart:1630:10)
E/flutter (13418): #9      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (13418): #10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (13418): #11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (13418): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (13418): 
E/flutter (13418): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#init on channel OneSignal)
E/flutter (13418): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (13418): <asynchronous suspension>
E/flutter (13418): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (13418): #2      OneSignal.init (package:onesignal_flutter/onesignal_flutter.dart:64:20)
E/flutter (13418): #3      main (package:app/main.dart:20:20)
E/flutter (13418): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (13418): #5      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (13418): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (13418): #7      _runZoned (dart:async/zone.dart:1630:10)
E/flutter (13418): #8      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (13418): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (13418): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (13418): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (13418): 
E/flutter (13418): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#setInFocusDisplayType on channel OneSignal)
E/flutter (13418): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (13418): <asynchronous suspension>
E/flutter (13418): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (13418): #2      OneSignal.setInFocusDisplayType (package:onesignal_flutter/onesignal_flutter.dart:161:20)
E/flutter (13418): #3      main (package:app/main.dart:27:20)
E/flutter (13418): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (13418): #5      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (13418): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (13418): #7      _runZoned (dart:async/zone.dart:1630:10)
E/flutter (13418): #8      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (13418): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (13418): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (13418): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (13418): 
E/flutter (13418): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#promptPermission on channel OneSignal)
E/flutter (13418): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (13418): <asynchronous suspension>
E/flutter (13418): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (13418): #2      OneSignal.promptUserForPushNotificationPermission (package:onesignal_flutter/onesignal_flutter.dart:147:37)
E/flutter (13418): #3      main (package:app/main.dart:30:26)
E/flutter (13418): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (13418): #5      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (13418): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (13418): #7      _runZoned (dart:async/zone.dart:1630:10)
E/flutter (13418): #8      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (13418): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (13418): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (13418): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

I believe that OneSignal was not inside my primary DEX file, which caused this problem.

I added a file app/multidex-config.pro which included these two lines:

```
-keep class com.onesignal.flutter.**  { *; }
-keep class com.onesignal.**  { *; }
```

But it is not working, still getting the same errors.

This is my app/build.gradle:

```
buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            useProguard true
            multiDexKeepProguard file('multidex-config.pro')
        }
        debug {
            minifyEnabled true
            shrinkResources true
            useProguard true
            multiDexKeepProguard file('multidex-config.pro')
        }
    }
```

**My Request:
I need an entire list of classes of One Signal in Android to add to this multidex-config.pro file.**

main.dart:

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  //Remove this method to stop OneSignal Debugging
  OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none);

  OneSignal.shared.init(
      "(hidden)",
      iOSSettings: {
        OSiOSSettings.autoPrompt: false,
        OSiOSSettings.inAppLaunchUrl: false
      }
  );
  OneSignal.shared.setInFocusDisplayType(OSNotificationDisplayType.notification);

// The promptForPushNotificationsWithUserResponse function will show the iOS push notification prompt. We recommend removing the following code and instead using an In-App Message to prompt for notification permission
  await OneSignal.shared.promptUserForPushNotificationPermission(fallbackToSettings: true);
  runApp(MyApp());
}
```

The first landing page of App:

```
@override
  void initState() {
    super.initState();
    OneSignal.shared
        .setNotificationOpenedHandler((OSNotificationOpenedResult result) async {
      try {
        var id = await result.notification.payload.additionalData["news_id"]
            .toString();
        if (id != "null") {
          Navigator.of(context).push(MaterialPageRoute(
              builder: (context) => NewsDetailFromPush(
                  news: News(id: id))));
        }
      } catch (e, stacktrace) {
        print("Open Push Notification Error: $e");
      }
    });
  }
```

**Environment**

1. OneSignal Flutter SDK: 2.6.2
1. How did you add the SDK to your project (eg. pub) : pubspec.yaml

**Steps to Reproduce Issue:**

1. As soon as the Android App is built and run, it showed these errors, and since OneSignal is initialized at main.dart, with these errors in OneSignal, other parts of the App cannot run, and the entire Android App is non-functional (white screen on Android emulator). No problem on iOS.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by SenChai2047** [comment]
First of all, although the errors come from OneSignal, I believe that it is NOT OneSignal that is causing the problem. But I still need your help. Let me explain.

OneSignal and the App was working fine before I added FaceBook Sign In and Apple Sign In and enabled MultiDEX. After that I uninstalled the FaceBook and Apple Sign In plugins and the App and OneSignal works fine again.

The reason for enabling MultiDEX is that there is a 65536 reference limit or otherwise called 64K Limit in Android. When there are too many functionalities that exceeds 65536 or 64K methods, Android has to enable MultiDEX. So the problem is neither related to FaceBook and Apple Sign In, but because there are too many functionalities in the App.

When MultiDEX is enabled, it has to decide which methods or functionalities go to the first set of 65536 methods to start the App. Those classes that are needed to start the App are declared in the primary DEX file. Other classes that are not needed when the App starts can be placed in the secondary DEX files and need not be manually declared. Android will use the classes in the primary DEX file to start the App.

Because OneSignal is needed when the App starts, **I need a list of classes that OneSignal uses, including the classes of the plugins that OneSignal uses, and the classes of the plugins that the plugins of OneSignal use, to declare in the primary DEX file (multidex-config.pro file)**, so that the App will have the necessary classes when the App starts.

So this above is my request.

I am finding you because only errors from OneSignal were found when the App started.

For your info, 
1. Version of Flutter: 1.22.5
2. Version of OneSignal_Flutter plugin: 2.6.2
3. OneSignal code and full error code and steps to reproduce: stated in this issue in the first message

SetLogLevel method is already included in my main.dart, please see my description on the issue in the first message, my code is copied there.

Thank you very much and I look forward to your reply.

**Comment by SenChai2047** [comment]
For a reference about the Android MultiDEX, see 
https://developer.android.com/studio/build/multidex#multidexkeepproguard-property

**Comment by jkasten2** [comment]
@SenChai2047 The symptoms does sound like a mutlidex issue, however you noted you set your minSdkVersion to 21 which is Android 5.0. This version using ART which does not have the issue needing to ensure some cases are in the main dex file.
> **Multidex support for Android 5.0 and higher**
Android 5.0 (API level 21) and higher uses a runtime called ART which natively supports loading multiple DEX files from APK files. ART performs pre-compilation at app install time which scans for classesN.dex files and compiles them into a single .oat file for execution by the Android device. Therefore, if your minSdkVersion is 21 or higher multidex is enabled by default, and you do not need the multidex library.

There could be something else at play here, maybe some proguard setting. Could you share a project reproducing the issue and / or your APK?
