### ISSUE TITLE
SetSubscriptionObserver doesn't return any value as in 2.6

### ISSUE THREAD

**Issue by rickydj** [OneSignal/OneSignal-Flutter-SDK#381]
**Description:**
Using v 3.0.0-beta2 when i try to initialize with setAppId, i must wait for a response when the subscription is changed, i've waiting for a response in setSubscriptionObserver to get the player_id, this used to send customized messages to each mobile connected, it have been working on 2.6.3 returning the object with the player_id

**Environment**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [VersiÃ³n 10.0.19042.928], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (3 available)

**Steps to Reproduce Issue:**

I made this code
<code>
Future<void> initPlatformState() async {
    OneSignal.shared.setNotificationWillShowInForegroundHandler(
      (OSNotificationReceivedEvent notification) {
        mensajes.alerta(
            titulo: "Notificacion", mensaje: notification.notification.body!);
      },
    );

    OneSignal.shared.setNotificationOpenedHandler(
      (OSNotificationOpenedResult result) {
        mensajes.alerta(
            titulo: "Notificacion", mensaje: result.notification.body!);
      },
    );

    OneSignal.shared.setPermissionObserver((changes) {
      print(changes);
    });

    OneSignal.shared.setSubscriptionObserver((changes) async {

      // This is the part where the code doesn't enter

      if (changes.to.userId != null) {
        await prefs.setPushID(changes.to.userId!); 
      }
    });

    await OneSignal.shared.setAppId("d17adbcb-e549-408b-9276-52524a3d2958");
    OneSignal.shared.disablePush(false);
  }
</code>

I debug my code from the emulator, with a fresh installation of the app, and three other emulators with different configurations and nothing

Someone knows how to get the player id using another way?

Thanks a lot

**Comment by rickydj** [comment]
Good day, i have to update this thread, i've changed my code to use an external user id, and this solves my problem, but now, when i started my application and then register the external user id, i should receive the push notificatioin, but my application crashes, this is my code

<code>
Future<void> initPlatformState() async {
    OneSignal.shared.setNotificationWillShowInForegroundHandler(
      (OSNotificationReceivedEvent notification) {
        mensajes.alerta(
            titulo: "Notificacion", mensaje: notification.notification.body!);
      },
    );

    OneSignal.shared.setNotificationOpenedHandler(
      (OSNotificationOpenedResult result) {
        mensajes.alerta(
            titulo: "Notificacion", mensaje: result.notification.body!);
      },
    );

    await OneSignal.shared.setAppId("d17adbcb-e549-408b-9276-52524a3d2958");

    OneSignal.shared.disablePush(false);
  }

/////////// Afther this registration i set the external user id in other point of my app /////////////

// Other code
      String random = randomAlphaNumeric(15);
      await prefs.setPushID(random);
      await OneSignal.shared.setExternalUserId(random);

//Other code
</code>

When the app executes the setNotificationOpenedHandler handler, it crashes with this stack;

<code>

Launching lib\main.dart on AOSP on IA Emulator in debug mode...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:55168/oOnyr4WWz-8=/ws
D/EGL_emulation( 9652): eglMakeCurrent: 0xcf809720: ver 3 0 (tinfo 0xcebef3d0)
D/eglCodecCommon( 9652): setVertexArrayObject: set vao to 0 (0) 1 0
I/tinel.teleappv( 9652): Waiting for a blocking GC ProfileSaver
I/tinel.teleappv( 9652): Background concurrent copying GC freed 21170(6MB) AllocSpace objects, 7(140KB) LOS objects, 49% free, 1539KB/3MB, paused 5.476ms total 58.407ms
I/tinel.teleappv( 9652): WaitForGcToComplete blocked ProfileSaver on ProfileSaver for 25.707ms
[38;5;244m[GETX] [39;49mInstance "GetMaterialController" has been created
[38;5;244m[GETX] [39;49mInstance "GetMaterialController" has been initialized
W/ComponentDiscovery( 9652): Class com.google.firebase.dynamicloading.DynamicLoadingRegistrar is not an found.
I/FirebaseApp( 9652): Device unlocked: initializing all Firebase APIs for app ONESIGNAL_SDK_FCM_APP_NAME
W/OneSignal( 9652): remoteNotificationReceivedHandler not setup, displaying normal OneSignal notification
D/onesignal( 9652): Created json raw payload: {vis=1, google.original_priority=normal, google.sent_time=1618523704868, pri=5, licon=https://img.onesignal.com/t/c183a670-3385-411d-9a81-5bfaccb64667.png, google.delivered_priority=normal, custom={"a":{"groupMessage":"registro"},"ti":"c04e4a65-3d08-4d53-8255-e5df45c2a3ec","i":"d145f360-75aa-4a85-8192-acbc6ae81e03","tn":"Registro"}, sound=id_com, bgn=1, google.c.sender.id=740258068655, oth_chnl=, title=Registro APP, google.message_id=0:1618523704879847%448e6de1f9fd7ecd, alert=Codigo de registro teleapp 441504, google.ttl=259200, from=740258068655}
D/AndroidRuntime( 9652): Shutting down VM
E/AndroidRuntime( 9652): FATAL EXCEPTION: main
E/AndroidRuntime( 9652): Process: com.telesentinel.teleappv3, PID: 9652
E/AndroidRuntime( 9652): java.lang.IllegalArgumentException: Unsupported value: {"groupMessage":"registro"}
E/AndroidRuntime( 9652): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:276)
E/AndroidRuntime( 9652): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:273)
E/AndroidRuntime( 9652): 	at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:38)
E/AndroidRuntime( 9652): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:99)
E/AndroidRuntime( 9652): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:83)
E/AndroidRuntime( 9652): 	at com.onesignal.flutter.FlutterRegistrarResponder$4.run(FlutterRegistrarResponder.java:73)
E/AndroidRuntime( 9652): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 9652): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 9652): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 9652): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 9652): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9652): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 9652): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/tinel.teleappv( 9652): Unknown chunk type '200'.
I/Process ( 9652): Sending signal. PID: 9652 SIG: 9
Lost connection to device.
Exited (sigterm)

</code>


Something similar have happened before to anyone?, i didn't find any answer about this problem

**Comment by Jeasmine** [comment]
Hey @rickydj  can you confirm that subscriptionObserver is working ok for you then? The second error that you pasted here, will be solved on the next release!

**Comment by Lomski** [comment]
Same issue. On app installation **getDeviceState** always null and SetSubscriptionObserver never fires. 
```
OneSignal.shared.setSubscriptionObserver((OSSubscriptionStateChanges changes) {
      print('-------------------------------------------');
      print(changes.to.userId);
      print(changes.from.userId);
      }
    });
```

<details>
<summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale ru_RU.UTF-8)
    • Flutter version 2.2.1 at /home/user/Programs/flutter
    • Framework revision 02c026b03c (8 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /home/user/Android/Sdk
    • Java binary at: /home/user/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/user/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • ONEPLUS A6010 (mobile)       • e29b8f89      • android-arm64  • Android 10 (API 29)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 81.0.4044.138

• No issues found!

```
</details>

Also i see this in onesignal logs:
```
D/OneSignal( 5194): OneSignalRestClient: POST RECEIVED JSON: {"success":true,"id":"b2e1ca2f-bfc0-4cdc-8f84-b4f1356f9b98"}
D/OneSignal( 5194): doCreateOrNewSession:response: {"success":true,"id":"b2e1ca2f-bfc0-4cdc-8f84-b4f1356f9b98"}
I/OneSignal( 5194): Device registered, UserId = b2e1ca2f-bfc0-4cdc-8f84-b4f1356f9b98
```

And on second app start getDeviceState return this user id.

**Comment by nan-li** [comment]
This looks related to https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/413, which has been fixed.
