### ISSUE TITLE
OneSignal and getPermissionSubscriptionState crash on Android

### ISSUE THREAD

**Issue by danielgomezrico** [OneSignal/OneSignal-Flutter-SDK#403]
**Description:**
After calling `getPermissionSubscriptionState` I get an error

```dart
 OneSignal.shared.getPermissionSubscriptionState().then((changes) {
```

**Environment**
```YAML
environment:
  sdk: 2.10.4
  flutter: 1.22.4

onesignal_flutter: 2.6.2
```

**Steps to Reproduce Issue:**
It happens every time

**Anything else:**
Log
```dart
I/flutter (12727): PlatformException(error, Attempt to invoke virtual method 'com.onesignal.OSSubscriptionState com.onesignal.OSPermissionSubscriptionState.getSubscriptionStatus()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'com.onesignal.OSSubscriptionState com.onesignal.OSPermissionSubscriptionState.getSubscriptionStatus()' on a null object reference
I/flutter (12727): 	at com.onesignal.flutter.OneSignalSerializer.convertPermissionSubscriptionStateToMap(OneSignalSerializer.java:47)
I/flutter (12727): 	at com.onesignal.flutter.OneSignalPlugin.getPermissionSubscriptionState(OneSignalPlugin.java:224)
I/flutter (12727): 	at com.onesignal.flutter.OneSignalPlugin.onMethodCall(OneSignalPlugin.java:104)
I/flutter (12727): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
I/flutter (12727): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
I/flutter (12727): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Flu
I/flutter (12727): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (12727): The following exception was thrown tag(null): message(Not handled error):
I/flutter (12727): PlatformException(error, Attempt to invoke virtual method 'com.onesignal.OSSubscriptionState com.onesignal.OSPermissionSubscriptionState.getSubscriptionStatus()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'com.onesignal.OSSubscriptionState com.onesignal.OSPermissionSubscriptionState.getSubscriptionStatus()' on a null object reference
I/flutter (12727): 	at com.onesignal.flutter.OneSignalSerializer.convertPermissionSubscriptionStateToMap(OneSignalSerializer.java:47)
I/flutter (12727): 	at com.onesignal.flutter.OneSignalPlugin.getPermissionSubscriptionState(OneSignalPlugin.java:224)
I/flutter (12727): 	at com.onesignal.flutter.OneSignalPlugin.onMethodCall(OneSignalPlugin.java:104)
I/flutter (12727): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
I/flutter (12727): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
I/flutter (12727): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
I/flutter (12727): 	at android.os.MessageQueue.nativePollOnce(Native M
I/flutter (12727): 
I/flutter (12727): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
I/flutter (12727): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
I/flutter (12727): <asynchronous suspension>
I/flutter (12727): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
I/flutter (12727): #3      OneSignal.getPermissionSubscriptionState (package:onesignal_flutter/onesignal_flutter.dart:219:24)
I/flutter (12727): #4      PushNotifier._initListeners (package:client/src/api/third_party/push_notifications/push_notifier.dart:130:22)
I/flutter (12727): #5      PushNotifier.init (package:client/src/api/third_party/push_notifications/push_notifier.dart:71:5)
I/flutter (12727): #6      _rootRunUnary (dart:async/zone.dart:1198:47)
I/flutter (12727): #7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
I/flutter (12727): #8      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
I/flutter (12727): #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
I/flutter (12727): #10     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
I/flutter (12727): #11     Future._comp
```

**Comment by emawby** [comment]
@danielgomezrico Hello is this still occurring for you? Have you tried updating to a newer version of the OneSignal Flutter SDK?

**Comment by nan-li** [comment]
There have been many changes and fixes since this issue was reported.
Due to that and no response, I will close this issue.
If anything changes, we can re-open if there are more reports.
