### ISSUE TITLE
javax.net.ssl.SSLHandshakeException on Onesignal 3.2.3

### ISSUE THREAD

**Issue by asbah007** [OneSignal/OneSignal-Flutter-SDK#491]
```
D/OneSignal(32325): Starting request to get Android parameters.
D/OneSignal(32325): OneSignalRestClient: Making request to: https://api.onesignal.com/apps/390310d8-0aba-4f2e-ad26-98c631caa4b3/android_params.js
W/OneSignal(32325): OneSignalRestClient: null Error thrown from network stack. 
W/OneSignal(32325): javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/OneSignal(32325): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
W/OneSignal(32325): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
W/OneSignal(32325): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
W/OneSignal(32325): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
W/OneSignal(32325): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
W/OneSignal(32325): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
W/OneSignal(32325): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
W/OneSignal(32325): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
W/OneSignal(32325): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
W/OneSignal(32325): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
W/OneSignal(32325): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
W/OneSignal(32325): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
W/OneSignal(32325): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
W/OneSignal(32325): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
W/OneSignal(32325): 	at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:183)
W/OneSignal(32325): 	at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:44)
W/OneSignal(32325): 	at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:112)
W/OneSignal(32325): 	at java.lang.Thread.run(Thread.java:919)
W/OneSignal(32325): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/OneSignal(32325): 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:674)
W/OneSignal(32325): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:551)
W/OneSignal(32325): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:507)
W/OneSignal(32325): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:426)
W/OneSignal(32325): 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:354)
W/OneSignal(32325): 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
W/OneSignal(32325): 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:89)
W/OneSignal(32325): 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:224)
W/OneSignal(32325): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:407)
W/OneSignal(32325): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/OneSignal(32325): 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
W/OneSignal(32325): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
W/OneSignal(32325): 	... 17 more
W/OneSignal(32325): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/OneSignal(32325): 	... 29 more
I/OneSignal(32325): Failed to get Android parameters, trying again in 90 seconds.

```

**Comment by jfishman1** [comment]
Hello, are you still having this issue?

Can you share a list of your dependencies in the app with version?

**Comment by jfishman1** [comment]
We had another report of this occurring due to an adblocker software. Please check if you also use adblocker software and either disable or whitelist OneSignal.
