### ISSUE TITLE
Plateform Exception Onesignal.setAppID

### ISSUE THREAD

**Issue by BenFredjSkander** [OneSignal/OneSignal-Flutter-SDK#500]
i' upgraded Onesignal SDK to the last version available and I'm getting this error in Sentry

```
PlatformException
PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
	at com.onesignal.n0.d(Unknown Source:21)
	at com.onesignal.V0.h1(Unknown Source:18)
	at com.onesignal.flutter.OneSignalPlugin.onMethodCall(:4)
	at e.b.b.a.i$a.a(Unknown Source:17)
	at io.flutter.embedding.engine.e.b.d(Unknown Source:25)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:7861)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
)
```

**Comment by jkasten2** [comment]
Closing in favor of already reported issue #494, recently provided an update on that issue https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/494#issuecomment-1022883737
