### ISSUE TITLE
Does not provide method of clicking on notification when the application is terminated or closed completely?

### ISSUE THREAD

**Issue by MuhamadHaydar** [OneSignal/OneSignal-Flutter-SDK#515]
**Description:**

Does not provide method of clicking on notification when the application is terminated or closed completely?

**Environment**

1. Onesignal_flutter 3.2.7 
2. Add it to pubspec.yaml

**Steps to Reproduce Issue:**

1. Install One Signal Flutter SDK uses pub.
2. Initialize for both Android and IOS. 
3. Initialize the SDK uses OneSignal.shared.init(your_app_id)

**Comment by jkasten2** [comment]
@MuhamadHaydar You should be able to use the

```dart
```

**Comment by MuhamadHaydar** [comment]
Yeah implemented already, but it's not working when the application is terminated totally, 
i would like go specific screen, but method won't be called when the app terminated.

**Comment by PrabinMaharjan** [comment]
i'm facing same issue

**Comment by edsonboldrini** [comment]
Getting these errors when tap notification on Android 11.

`onesignal_flutter: ^3.2.7`

```
D/OneSignal( 8784): OneSignalRestClient: Making request to: https://api.onesignal.com/notifications/dbac7f2e-7adb-4263-a592-c62b5b7dbbd9
D/OneSignal( 8784): OneSignalRestClient: PUT SEND JSON: {"app_id":"167bd056-ac99-48e3-bfae-8730c2e773e8","player_id":"81746f6c-466d-4d14-bb04-9aafb9c7ff0d","opened":true,"device_type":1}
D/DecorView[]( 8784): getWindowModeFromSystem  windowmode is 1
D/DecorView( 8784): createDecorCaptionView windowingMode:1 mWindowMode 1 isFullscreen: true
W/OneSignal( 8784): OneSignalRestClient: PUT Error thrown from network stack.
W/OneSignal( 8784): java.net.SocketException: Connection reset
W/OneSignal( 8784): 	at java.net.SocketInputStream.read(SocketInputStream.java:215)
W/OneSignal( 8784): 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
W/OneSignal( 8784): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
W/OneSignal( 8784): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
W/OneSignal( 8784): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
W/OneSignal( 8784): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
W/OneSignal( 8784): 	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
W/OneSignal( 8784): 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
W/OneSignal( 8784): 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
W/OneSignal( 8784): 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
W/OneSignal( 8784): 	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
W/OneSignal( 8784): 	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
W/OneSignal( 8784): 	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
W/OneSignal( 8784): 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
W/OneSignal( 8784): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
W/OneSignal( 8784): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
W/OneSignal( 8784): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
W/OneSignal( 8784): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
W/OneSignal( 8784): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
W/OneSignal( 8784): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
W/OneSignal( 8784): 	at com.google.firebase.perf.network.InstrURLConnectionBase.getResponseCode(InstrURLConnectionBase.java:185)
W/OneSignal( 8784): 	at com.google.firebase.perf.network.InstrHttpsURLConnection.getResponseCode(InstrHttpsURLConnection.java:99)
W/OneSignal( 8784): 	at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:197)
W/OneSignal( 8784): 	at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:46)
W/OneSignal( 8784): 	at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:114)
W/OneSignal( 8784): 	at java.lang.Thread.run(Thread.java:923)
D/OneSignal( 8784): onActivityDestroyed: com.onesignal.NotificationOpenedReceiver@2cabe55
D/OneSignal( 8784): curActivity is NOW: null
W/OneSignal( 8784): HTTP code: -1 sending Notification Opened Failed
W/OneSignal( 8784): java.net.SocketException: Connection reset
W/OneSignal( 8784): 	at java.net.SocketInputStream.read(SocketInputStream.java:215)
W/OneSignal( 8784): 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
W/OneSignal( 8784): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
W/OneSignal( 8784): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
W/OneSignal( 8784): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
W/OneSignal( 8784): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
W/OneSignal( 8784): 	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
W/OneSignal( 8784): 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
W/OneSignal( 8784): 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
W/OneSignal( 8784): 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
W/OneSignal( 8784): 	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
W/OneSignal( 8784): 	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
W/OneSignal( 8784): 	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
W/OneSignal( 8784): 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
W/OneSignal( 8784): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
W/OneSignal( 8784): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
W/OneSignal( 8784): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
W/OneSignal( 8784): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
W/OneSignal( 8784): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
W/OneSignal( 8784): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
W/OneSignal( 8784): 	at com.google.firebase.perf.network.InstrURLConnectionBase.getResponseCode(InstrURLConnectionBase.java:185)
W/OneSignal( 8784): 	at com.google.firebase.perf.network.InstrHttpsURLConnection.getResponseCode(InstrHttpsURLConnection.java:99)
W/OneSignal( 8784): 	at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:197)
W/OneSignal( 8784): 	at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:46)
W/OneSignal( 8784): 	at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:114)
W/OneSignal( 8784): 	at java.lang.Thread.run(Thread.java:923)
D/OneSignal( 8784): Running complete from OSNotificationOpenedResult timeout runnable!
D/OneSignal( 8784): OSNotificationOpenedResult complete called with opened: false
D/OneSignal( 8784): Running destroyTimeout with runnable: com.onesignal.OSNotificationOpenedResult$1@10f206a

```

**Comment by jkasten2** [comment]
@MuhamadHaydar @PrabinMaharjan I attempted to reproduce the issue without any luck.

## Version and project
Flutter Channel stable, 2.5.3
onesignal_flutter 3.2.7

Tested with the [example project](https://github.com/OneSignal/OneSignal-Flutter-SDK/tree/main/example) in this repo.

## Devices
Tested on an iOS 14.4 device and an Android 12 emulator.

## Steps attempted
1. Swipe away app
2. Send notification
3. Tap on notification
4. Observer debugging code in `setNotificationOpenedHandler` fires.
 

# Need more details
Let us know if any of the above differs. Please share you OneSignal code and where you are calling it to help narrow down the issue.

Note, if you call `setNotificationOpenedHandler` more than once only the most recent callback you gave it will fire.

**Comment by jkasten2** [comment]
@edsonboldrini The message about "java.net.SocketException: Connection reset" in your logcat are not related. It seems your device has an issue connecting to api.onesignal.com as it it getting general network errors.

**Comment by MuhamadHaydar** [comment]
@jkasten2 
Thank you for your response, I tested your project on both android & iOS, for whole cases foreground, background, terminated, It was working well, Thanks.
But please refer that it's working even if the app is terminated in the documentation, because as i read the documentation totally, you have not referred that. 
Thanks

**Comment by jkasten2** [comment]
@MuhamadHaydar Thanks for trying out the example project to confirm it works for you. However are you still seeing an issue with the terminated case in your project?

Thanks for the feedback on the documentation, we will update it with more details to make this clear.
