### ISSUE TITLE
Runner (true) and OneSignalNotificationServiceExtension (false) do not both set use_frameworks!.

### ISSUE THREAD

**Issue by illukinati** [OneSignal/OneSignal-Flutter-SDK#53]
I use onesignal ^1.0.5, I already follow this step https://documentation.onesignal.com/docs/flutter-sdk-setup but still I cannot run my application because of `use_frameworkrs!` thing.

```
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
      Using `ARCHS` setting to build architectures of target `Pods-OneSignalNotificationServiceExtension`: (``)

    Finding Podfile changes
      - Flutter
      - OneSignal
      - onesignal
      - shared_preferences
      - url_launcher
      - web_vuw

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `onesignal` from `.symlinks/plugins/onesignal/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    -> Fetching podspec for `web_vuw` from `.symlinks/plugins/web_vuw/ios`

    Resolving dependencies of `Podfile`
    [!] Unable to integrate the following embedded targets with their respective host targets (a host target is a "parent" target which embeds a "child" target like a framework or extension):

    - Runner (true) and OneSignalNotificationServiceExtension (false) do not both set use_frameworks!.

    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:377:in `analyze_host_targets_in_podfile'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:399:in `generate_targets'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:91:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `<main>'

Finished with error: Error running pod install
```

this is my flutter doctor -v

```
[✓] Flutter (Channel master, v1.1.10-pre.197, on Mac OS X 10.14.2 18C54, locale en-JP)
    • Flutter version 1.1.10-pre.197 at /Users/ekoprasetyo/flutter
    • Framework revision bb5663d2d8 (10 hours ago), 2019-01-27 09:43:09 -0800
    • Engine revision 9b6d5031a3
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 a5030ed92f)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ekoprasetyo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • SM J710F • 52035fadec69a3f9 • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

have anything idea what happened ?

**Comment by Nightsd01** [comment]
Please post your Podfile, looks like you probably made a mistake when setting up the extension service. 

Also, if your Podfile contains `use_frameworks!` you will not be able to use our SDK in its current form - end of story, unfortunately. We already have an issue for this.

**Comment by illukinati** [comment]
@Nightsd01 sorry, forgot to attach the podfile.
Yes, my podfile contains `use_frameworks!` right now.
so you will give me advice to wait until OneSignal fix this ?

```
# Uncomment this line to define a global platform for your project
 platform :ios, '10.2'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

```

**Comment by DarthWindu** [comment]
@Nightsd01 is compatibility with `use_frameworks!` planned? I have another dependency that needs it :(

**Comment by rgomezp** [comment]
Please see #42 for all the information regarding this issue

**Comment by topeomot2** [comment]
I am still getting the issue even with the latest update
[✓] Flutter (Channel beta, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale en-NG)
    • Flutter version 1.7.8+hotfix.4 at /Users/temitopeomotunde/sdks/flutter
    • Framework revision 20e59316b8 (10 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/temitopeomotunde/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.4 Preview.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b22)

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[!] Connected device
    ! No devices available

Pubspec.yaml
```
dependencies:
  flutter:
    sdk: flutter
  meta: '>=1.1.0 <2.0.0'
  dio: ^2.1.7
  jose: ^0.1.2
  async: ^2.0.8
  rxdart: ^0.20.0
  shared_preferences: ^0.4.3
  package_info: ^0.3.2
  url_launcher: ^4.0.1
  transparent_image: ^0.1.0
  firebase_core: ^0.4.0+6
  firebase_analytics: ^3.0.2
  cloud_functions: ^0.4.0
  cloud_firestore: ^0.12.1
  firebase_dynamic_links: ^0.4.0+4
  flutter_local_notifications: ^0.7.1+1
  intl: ^0.15.8
  share: ^0.6.1+1
  numberpicker: ^1.0.0
  flutter_webview_plugin: ^0.3.5
  charts_flutter: ^0.6.0
  sqflite: ^1.1.5
  launch_review: ^2.0.0
  pdf: ^1.3.10
  printing: ^2.1.3
  flutter_user_agent: ^1.0.1
  tuple: ^1.0.2
  provider: ^3.0.0
  onesignal_flutter: ^2.0.0
  image: ^2.1.4
```

 Runner (true) and OneSignalNotificationServiceExtension (false) do not both set use_frameworks!.

**Comment by topeomot2** [comment]
I solve it by adding use_frameworks! to the OneSignalNotificationServiceExtension target

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end

**Comment by andrefigueira93** [comment]
> I solve it by adding use_frameworks! to the OneSignalNotificationServiceExtension target
> 
> ```
> target 'OneSignalNotificationServiceExtension' do
>   use_frameworks!
>   pod 'OneSignal', '>= 2.9.3', '< 3.0'
> end
> ```

Solved it!

**Comment by mrimran** [comment]
> I solve it by adding use_frameworks! to the OneSignalNotificationServiceExtension target
> 
> ```
> target 'OneSignalNotificationServiceExtension' do
>   use_frameworks!
>   pod 'OneSignal', '>= 2.9.3', '< 3.0'
> end
> ```

Thank you very much man, you saved lot of our time :)

**Comment by macabeus** [comment]
Following @topeomot2 works for me.... but is it a good approach? As long @Nightsd01 said before, OneSignal's SDK doesn't support frameworks, and it's look like a time bomb

**Comment by caiogranero** [comment]
Anyone who add `use_frameworks` in OneSignal target was able to archieve the app for publish?

**Comment by danielgomezrico** [comment]
@caiogranero You need to add `use_frameworks!` to the OneSignal target also like:

```
target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end
```

I tried that because I got an error just after creating the service as the docs mention, error:
```
$ pod install
Analyzing dependencies
[!] Unable to integrate the following embedded targets with their respective host targets (a host target is a "parent" target which embeds a "child" target like a framework or extension):

- Runner (true) and OneSignalNotificationServiceExtension (false) do not both set use_frameworks!.
```

**Comment by dorianmariefr** [comment]
I'm getting:

```
[!] Unable to find host target(s) for OneSignalNotificationServiceExtension. Please add the host targets for the embedded targets to the Podfile.
Certain kinds of targets require a host target. A host target is a "parent" target which embeds a "child" target. These are example types of targets that need a host target:
- Framework
- App Extension
- Watch OS 1 Extension
- Messages Extension (except when used with a Messages Application)
```

even after adding `use_framworks!`

here is my Podfile:

```
require_relative "../node_modules/react-native/scripts/react_native_pods"
require_relative "../node_modules/@react-native-community/cli-platform-ios/native_modules"
require_relative "../node_modules/react-native-unimodules/cocoapods"

platform :ios, "10.0"

target "socializus" do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(path: config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target "OneSignalNotificationServiceExtension" do
  use_frameworks!
  pod "OneSignal", ">= 3.0", "< 4.0"
end
```

**Comment by ChandAbdullah** [comment]
Read the documentation of [Flutter SDK Setup for Onesignal](https://documentation.onesignal.com/docs/flutter-sdk-setup)

**Comment by lucianolopezz** [comment]
> I solve it by adding use_frameworks! to the OneSignalNotificationServiceExtension target
> 
> ```
> target 'OneSignalNotificationServiceExtension' do
>   use_frameworks!
>   pod 'OneSignal', '>= 2.9.3', '< 3.0'
> end
> ```

Thank you very much bro!

**Comment by kaiquen** [comment]
@dorianmariecom 
I'm having the same problem! Did you manage to solve it?

`[!] Unable to find host target(s) for OneSignalNotificationServiceExtension. Please add the host targets for the embedded targets to the Podfile.
Certain kinds of targets require a host target. A host target is a "parent" target which embeds a "child" target. These are example types of targets that need a host target:
- Framework
- App Extension
- Watch OS 1 Extension
- Messages Extension (except when used with a Messages Application)`

**Comment by shalinipremi** [comment]
> I solve it by adding use_frameworks! to the OneSignalNotificationServiceExtension target
> 
> ```
> target 'OneSignalNotificationServiceExtension' do
>   use_frameworks!
>   pod 'OneSignal', '>= 2.9.3', '< 3.0'
> end
> ```

thank you so much , it worked for me
