### ISSUE TITLE
Users subscription state is automatically being changed to "Never Subscribed" 

### ISSUE THREAD

**Issue by mueksh-b** [OneSignal/OneSignal-Flutter-SDK#548]
**Description:**

Some users are randomly being unsubscribed from notifications. When a user starts using the app then its subscription state automatically changed from Subscribed to Never Subscribed (checking in OneSignal Dashboard) and after that, if the user closes the app and starts again the state changes back to Subscribed (Not always). 

![image](https://user-images.githubusercontent.com/24774694/167126916-4767ed3a-ead2-4c3c-8249-f2581ba39b60.png)

Note: I have only tested on Android.

**Environment**

onesignal_flutter: ^3.3.0
Android versions: 11, 12

**Steps to Reproduce Issue:**

1.  Start App 
2. Close App
3. Repeat Steps 1, 2

Logs when user changed to Never Subscribed:-

```
2022-05-06 16:43:25.892 2359-4234/com.walkinclips.walk_in_clips E/WM-WorkerWrapper: Work [ id=bb2c32a5-9f22-48e0-9bbd-df388a9bbcaf, tags={ FOCUS_LOST_WORKER_TAG, com.onesignal.OSFocusHandler$OnLostFocusWorker } ] failed because it threw an exception/error
    java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
        at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
        at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
        at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:311)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
        at com.onesignal.OSUtils.packageInstalledAndEnabled(OSUtils.java:275)
        at com.onesignal.OSUtils.isGMSInstalledAndEnabled(OSUtils.java:288)
        at com.onesignal.OSUtils.supportsGooglePush(OSUtils.java:330)
        at com.onesignal.OSUtils.getDeviceType(OSUtils.java:349)
        at com.onesignal.OSUtils.isAndroidDeviceType(OSUtils.java:371)
        at com.onesignal.LocationController.isGooglePlayServicesAvailable(LocationController.java:337)
        at com.onesignal.LocationController.onFocusChange(LocationController.java:325)
        at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1329)
        at com.onesignal.OSFocusHandler$Companion.onLostFocusDoWork(OSFocusHandler.kt:139)
        at com.onesignal.OSFocusHandler$OnLostFocusWorker.doWork(OSFocusHandler.kt:118)
        at androidx.work.Worker$1.run(Worker.java:86)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2022-05-06 16:43:29.207 2359-2359/com.walkinclips.walk_in_clips V/OneSignal: Initializing the OneSignal Flutter SDK (3.3.0)
2022-05-06 16:43:30.038 2359-2359/com.walkinclips.walk_in_clips D/OneSignal: Adding a task to the pending queue with ID: 1
2022-05-06 16:43:30.040 2359-2359/com.walkinclips.walk_in_clips D/OneSignal: startPendingTasks with task queue quantity: 1
2022-05-06 16:43:30.068 2359-2359/com.walkinclips.walk_in_clips D/OneSignal: OneSignal InAppMessageTracker initInfluencedTypeFromCache: OSChannelTracker{tag=iam_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}
2022-05-06 16:43:30.068 2359-4276/com.walkinclips.walk_in_clips D/OneSignal: Attempted to clean 6 month old IAM data, but none exists!
2022-05-06 16:43:30.068 2359-2359/com.walkinclips.walk_in_clips D/OneSignal: OneSignal NotificationTracker initInfluencedTypeFromCache: OSChannelTracker{tag=notification_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}
2022-05-06 16:43:30.069 2359-4275/com.walkinclips.walk_in_clips D/OneSignal: Retrieved IAMs from DB redisplayedInAppMessages: []
2022-05-06 16:43:30.069 2359-4275/com.walkinclips.walk_in_clips I/OneSignal: Last Pending Task has ran, shutting down
2022-05-06 16:43:30.077 2359-2359/com.walkinclips.walk_in_clips D/OneSignal: OneSignal getUnattributedUniqueOutcomeEventsSentByChannel: []
2022-05-06 16:43:30.163 2359-2359/com.walkinclips.walk_in_clips V/OneSignal: appContext set and cached app id found, calling setAppId with: bf52b7d0-c460-4d50-8bce-64c68ca2cc54
2022-05-06 16:43:30.165 2359-2359/com.walkinclips.walk_in_clips V/OneSignal: setAppId called with id: bf52b7d0-c460-4d50-8bce-64c68ca2cc54 changing id from: null
2022-05-06 16:43:30.168 2359-2359/com.walkinclips.walk_in_clips V/OneSignal: Starting OneSignal initialization!
2022-05-06 16:43:30.187 2359-2359/com.walkinclips.walk_in_clips V/OneSignal: No class found, not setting up OSRemoteNotificationReceivedHandler
2022-05-06 16:43:30.190 2359-2359/com.walkinclips.walk_in_clips V/OneSignal: OneSignal SDK initialization delayed, waiting for remote params.
2022-05-06 16:43:30.199 2359-2359/com.walkinclips.walk_in_clips D/OneSignal: Starting request to get Android parameters.
2022-05-06 16:43:30.233 2359-2359/com.walkinclips.walk_in_clips V/OneSignal: setAppId called with id: bf52b7d0-c460-4d50-8bce-64c68ca2cc54 changing id from: null
2022-05-06 16:43:30.234 2359-2359/com.walkinclips.walk_in_clips V/OneSignal: Starting OneSignal initialization!
2022-05-06 16:43:30.235 2359-4309/com.walkinclips.walk_in_clips D/OneSignal: OneSignalRestClient: Making request to: https://api.onesignal.com/apps/bf52b7d0-c460-4d50-8bce-64c68ca2cc54/android_params.js?player_id=73045731-0fbb-4f73-8feb-5b8428777b74
2022-05-06 16:43:30.239 2359-2359/com.walkinclips.walk_in_clips V/OneSignal: No class found, not setting up OSRemoteNotificationReceivedHandler
2022-05-06 16:43:30.241 2359-2359/com.walkinclips.walk_in_clips V/OneSignal: OneSignal SDK initialization delayed, waiting for remote params.
2022-05-06 16:43:30.268 2359-4309/com.walkinclips.walk_in_clips D/OneSignal: OneSignalRestClient: Adding header if-none-match: W/"0b830f156b17708f25fbfd87c13834b8"
2022-05-06 16:43:30.301 2359-2359/com.walkinclips.walk_in_clips E/OneSignal: promptPermission() is not applicable in Android
2022-05-06 16:43:30.336 2359-2359/com.walkinclips.walk_in_clips E/OneSignal: promptPermission() is not applicable in Android
2022-05-06 16:43:33.912 2359-4309/com.walkinclips.walk_in_clips V/OneSignal: OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/apps/bf52b7d0-c460-4d50-8bce-64c68ca2cc54/android_params.js?player_id=73045731-0fbb-4f73-8feb-5b8428777b74
2022-05-06 16:43:33.916 2359-4309/com.walkinclips.walk_in_clips D/OneSignal: OneSignalRestClient: GET - Using Cached response due to 304: {"awl_list":{},"android_sender_id":"452741034891","chnl_lst":[],"outcomes":{"direct":{"enabled":false},"indirect":{"notification_attribution":{"minutes_since_displayed":60,"limit":10},"enabled":false},"unattributed":{"enabled":false}},"receive_receipts_enable":false}
2022-05-06 16:43:33.945 2359-4365/com.walkinclips.walk_in_clips D/OneSignal: OneSignal saveInfluenceParams: InfluenceParams{indirectNotificationAttributionWindow=60, notificationLimit=10, indirectIAMAttributionWindow=1440, iamLimit=10, directEnabled=false, indirectEnabled=false, unattributedEnabled=false}
2022-05-06 16:43:33.952 2359-4365/com.walkinclips.walk_in_clips D/OneSignal: reassignDelayedInitParams with appContext: android.app.Application@fdde8fb
2022-05-06 16:43:33.953 2359-4365/com.walkinclips.walk_in_clips V/OneSignal: setAppId called with id: bf52b7d0-c460-4d50-8bce-64c68ca2cc54 changing id from: null
2022-05-06 16:43:33.955 2359-4365/com.walkinclips.walk_in_clips V/OneSignal: Starting OneSignal initialization!
2022-05-06 16:43:33.969 2359-4365/com.walkinclips.walk_in_clips V/OneSignal: No class found, not setting up OSRemoteNotificationReceivedHandler
2022-05-06 16:43:33.990 2359-4365/com.walkinclips.walk_in_clips D/OneSignal: OneSignal handleActivityLifecycleHandler inForeground: true
2022-05-06 16:43:34.104 2359-4365/com.walkinclips.walk_in_clips D/OneSignal: Application foregrounded focus time: 2685350938
2022-05-06 16:43:34.281 2359-4365/com.walkinclips.walk_in_clips D/OneSignal: isPastOnSessionTime currentTimeMillis: 1651835614223 lastSessionTime: 1651835605861 difference: 8362
2022-05-06 16:43:34.319 2359-4365/com.walkinclips.walk_in_clips D/OneSignal: Continue on same session with appEntryState: APP_CLOSE
2022-05-06 16:43:34.332 2359-4365/com.walkinclips.walk_in_clips D/OneSignal: OneSignal SessionManager attemptSessionUpgrade with entryAction: APP_CLOSE
2022-05-06 16:43:34.345 2359-4365/com.walkinclips.walk_in_clips D/OneSignal: OneSignal SessionManager attemptSessionUpgrade try UNATTRIBUTED to INDIRECT upgrade
2022-05-06 16:43:34.371 2359-4365/com.walkinclips.walk_in_clips D/OneSignal: Trackers after update attempt: [OSChannelTracker{tag=notification_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}, OSChannelTracker{tag=iam_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}]
2022-05-06 16:43:34.372 2359-4365/com.walkinclips.walk_in_clips D/OneSignal: OneSignal SessionManager sendSessionEndingWithInfluences with influences: []
2022-05-06 16:43:34.372 2359-4365/com.walkinclips.walk_in_clips D/OneSignal: initWithCachedInAppMessages: null
2022-05-06 16:43:34.397 2359-4365/com.walkinclips.walk_in_clips D/OneSignal: LocationController sendAndClearPromptHandlers from non prompt flow
2022-05-06 16:43:34.401 2359-4365/com.walkinclips.walk_in_clips D/OneSignal: LocationController startGetLocation with lastLocation: null
2022-05-06 16:43:35.626 2359-4365/com.walkinclips.walk_in_clips V/OneSignal: OneSignal SDK initialization done.
2022-05-06 16:43:35.641 2359-4365/com.walkinclips.walk_in_clips D/OneSignal: startPendingTasks with task queue quantity: 0
2022-05-06 16:43:37.137 2359-4394/com.walkinclips.walk_in_clips I/OneSignal: Device registered, push token = fzERee42TpKSWR4eFLRdNb:APA91bHkNXG5of3WnnVzBTlCjWxlDv6SVfrVJJalAZhvketczvq-i2gp9Odow57uYVne5dEr9tI5SkefdA_Y5thNdPcLG5Gda8pUywiQfd2QzjLXbqZC-nss4E2Q-OGd-xutiF2J_15v
2022-05-06 16:43:37.145 2359-4394/com.walkinclips.walk_in_clips D/OneSignal: registerForPushToken completed with id: fzERee42TpKSWR4eFLRdNb:APA91bHkNXG5of3WnnVzBTlCjWxlDv6SVfrVJJalAZhvketczvq-i2gp9Odow57uYVne5dEr9tI5SkefdA_Y5thNdPcLG5Gda8pUywiQfd2QzjLXbqZC-nss4E2Q-OGd-xutiF2J_15v status: 1
2022-05-06 16:43:37.150 2359-4394/com.walkinclips.walk_in_clips D/OneSignal: registerUser:registerForPushFired:true, locationFired: false, remoteParams: com.onesignal.OneSignalRemoteParams$2@585c455, appId: bf52b7d0-c460-4d50-8bce-64c68ca2cc54
2022-05-06 16:43:37.153 2359-4394/com.walkinclips.walk_in_clips D/OneSignal: registerUser not possible
2022-05-06 16:43:47.947 2359-4370/com.walkinclips.walk_in_clips D/OneSignal: GMSLocationController GoogleApiClientListener onConnected lastLocation: null
2022-05-06 16:43:48.292 2359-4370/com.walkinclips.walk_in_clips D/OneSignal: GMSLocationController GoogleApiClientListener lastLocation: Location[fused 26.908736,75.740570 hAcc=16 et=+31d1h55m8s104ms alt=378.79998779296875 vel=0.15770127 bear=0.14802215 vAcc=3 sAcc=1 bAcc=180 {Bundle[EMPTY_PARCEL]}]
2022-05-06 16:43:48.527 2359-4370/com.walkinclips.walk_in_clips D/OneSignal: LocationController fireCompleteForLocation with location: Location[fused 26.908736,75.740570 hAcc=16 et=+31d1h55m8s104ms alt=378.79998779296875 vel=0.15770127 bear=0.14802215 vAcc=3 sAcc=1 bAcc=180 {Bundle[EMPTY_PARCEL]}]
2022-05-06 16:43:48.624 2359-4370/com.walkinclips.walk_in_clips D/OneSignal: registerUser:registerForPushFired:true, locationFired: true, remoteParams: com.onesignal.OneSignalRemoteParams$2@585c455, appId: bf52b7d0-c460-4d50-8bce-64c68ca2cc54
2022-05-06 16:43:48.760 2359-4370/com.walkinclips.walk_in_clips D/OneSignal: LocationController scheduleUpdate lastTime: 66 minTime: 300000
2022-05-06 16:43:48.882 2359-4370/com.walkinclips.walk_in_clips V/OneSignal: OSSyncService scheduleLocationUpdateTask:delayMs: 299934
2022-05-06 16:43:48.897 2359-4370/com.walkinclips.walk_in_clips V/OneSignal: OSBackgroundSync scheduleSyncServiceAsJob:atTime: 299934
2022-05-06 16:43:48.933 2359-4370/com.walkinclips.walk_in_clips I/OneSignal: OSBackgroundSync scheduleSyncServiceAsJob:result: 1
2022-05-06 16:43:48.969 2359-4370/com.walkinclips.walk_in_clips D/OneSignal: GMSLocationController GoogleApiClient requestLocationUpdates!
2022-05-06 16:43:49.303 2359-4476/com.walkinclips.walk_in_clips D/OneSignal: registerUserTask calling readyToUpdate
2022-05-06 16:43:49.527 2359-4370/com.walkinclips.walk_in_clips D/OneSignal: GMSLocationController onLocationChanged: Location[fused 26.908736,75.740570 hAcc=16 et=+31d1h55m8s104ms alt=378.79998779296875 vel=0.15770127 bear=0.14802215 vAcc=3 sAcc=1 bAcc=180 {Bundle[EMPTY_PARCEL]}]
2022-05-06 16:43:50.510 2359-4477/com.walkinclips.walk_in_clips I/OneSignal: Restoring notifications
2022-05-06 16:43:50.534 2359-4477/com.walkinclips.walk_in_clips I/OneSignal: Querying DB for notifications to restore: created_time > 1651230830 AND dismissed = 0 AND opened = 0 AND is_summary = 0 AND expire_time > 1651835630
2022-05-06 16:43:55.238 2359-4368/com.walkinclips.walk_in_clips D/OneSignal: UserStateSynchronizer internalSyncUserState from session call: false jsonBody: {"loc_acc":16.264,"loc_type":1,"lat":26.908736,"long":75.7405696,"loc_bg":false,"loc_time_stamp":1651835571268,"app_id":"bf52b7d0-c460-4d50-8bce-64c68ca2cc54"}
2022-05-06 16:43:55.263 2359-4541/com.walkinclips.walk_in_clips D/OneSignal: OneSignalRestClient: Making request to: https://api.onesignal.com/players/73045731-0fbb-4f73-8feb-5b8428777b74
2022-05-06 16:43:55.280 2359-4541/com.walkinclips.walk_in_clips D/OneSignal: OneSignalRestClient: PUT SEND JSON: {"loc_acc":16.264,"loc_type":1,"lat":26.908736,"long":75.7405696,"loc_bg":false,"loc_time_stamp":1651835571268,"app_id":"bf52b7d0-c460-4d50-8bce-64c68ca2cc54"}
2022-05-06 16:43:55.965 2359-4541/com.walkinclips.walk_in_clips V/OneSignal: OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/players/73045731-0fbb-4f73-8feb-5b8428777b74
2022-05-06 16:43:55.978 2359-4541/com.walkinclips.walk_in_clips D/OneSignal: OneSignalRestClient: Successfully finished request to: https://api.onesignal.com/players/73045731-0fbb-4f73-8feb-5b8428777b74
2022-05-06 16:43:56.329 2359-4541/com.walkinclips.walk_in_clips D/OneSignal: OneSignalRestClient: PUT RECEIVED JSON: {"success":true}
```

**Comment by rohanbanksathi** [comment]
Was about to post the same thing, this is going on randomly. Sometimes it works and sometimes it is giving "Never Subscribed" error. The app was working fine and is in production, suddenly I am seeing almost all of the users are "Never Subscribed" now.

I have triple checked the code, after clearing and uninstalling the same APK multiple times, user gets subscribed sometimes but then again if we go to background or reinstall, they get converted to "Never Subscribed"

**Comment by dlipford360** [comment]
Wow I just found your issue after googling. I have a similar issue on my use of the react-onesignal library. If I solely setEmail(email) the user is subscribed fine with a checkmark. if I follow the setEmail with a setExternalUserId("userid123") it will cause the user to be "Never Subscribed". Good Luck!

**Comment by pablobrodt** [comment]
Im having the sabe issue, but in react-native. Haven't found much information around.

@mueksh-b do you know the android version of the devices that this is hapenning? I have a Xiaomi Mi A3 that works fine, and a Motorola with Android 12 that has the problem.

**Comment by leovazquezz1** [comment]
Same here for react native SDK. What is happening is very rare. In mi case I get the registration from the device and save it to server. In the device it all looks good as registered. I get the id from the api but after a few seconds I send a notification to the device and one signal responds as invalid id. 


<img width="1111" alt="Screen Shot 2022-05-06 at 5 57 41 PM 2" src="https://user-images.githubusercontent.com/28604559/167223141-92e1acbf-7fa2-4de5-a295-9e485cd35721.png">


Don't know what to do

**Comment by rohankandwal** [comment]
We are seeing the same thing, Onesignal is reporting success in creating playerID and sending all the parameters as well. Sometimes it shows subscribed for few minutes then automatically it goes to "Never Subscribed".

There are no previous tickets on any OneSignal SDK which leads for me to believe this is an issue with OneSignal itself, server side.

**Comment by rohankandwal** [comment]
> Im having the sabe issue, but in react-native. Haven't found much information around.
> 
> @mueksh-b do you know the android version of the devices that this is hapenning? I have a Xiaomi Mi A3 that works fine, and a Motorola with Android 12 that has the problem.

This is happening randomly for me, few users are facing this issue which few are subscribed so I don't think it's an OS specific issue.

**Comment by mueksh-b** [comment]
> Im having the sabe issue, but in react-native. Haven't found much information around.
> 
> @mueksh-b do you know the android version of the devices that this is hapenning? I have a Xiaomi Mi A3 that works fine, and a Motorola with Android 12 that has the problem.

I don't think that it's OS-specific, I have tried it on 3 different devices and faced the same issue on all devices.

**Comment by dlipford360** [comment]
https://status.onesignal.com/incidents/r7k5mjd3n9kz they supposedly came out with a fix.
