### ISSUE TITLE
Crashes app on China device (NullPointerException)

### ISSUE THREAD

**Issue by npduoc** [OneSignal/OneSignal-Flutter-SDK#553]
**Description:**

Hello there,
When I clicked on the notification, my app had been crashed.
This terrible issue appears only on the release version, debug version does not encounter it.
Please help me resolve it.
Thank you a lot.

**Environment**

Flutter doctor
![image](https://user-images.githubusercontent.com/100331782/169266371-b1ae9ff1-5d5b-4c10-adb2-26d25426e34c.png)

**Steps to Reproduce Issue:**

Video:
https://www.veed.io/view/6a209137-f79e-4ac8-8463-b63327aa6561?sharingWidget=true
Device Info:
- Oppo F11
- Android version: 11

**Anything else:**

This is the log from Firebase Crashlytics.
And my source does not exist MainActivity.java:224 line.

```
Fatal Exception: java.lang.NullPointerException
       at com.example.longchau.MainActivity.onNewIntent(MainActivity.java:224)
       at android.app.Activity.performNewIntent(Activity.java:8166)
       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1409)
       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1422)
       at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:4006)
       at android.app.ActivityThread.handleNewIntent(ActivityThread.java:4018)
       at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2350)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:8312)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

**Comment by jkasten2** [comment]
@npduoc Thanks for the details. Can you get the crash from the logcat from the device? That stacktrace should provide more details and may show the correct line number.

**Comment by npduoc** [comment]
@jkasten2 Currently, I have not logcat. I will get this device and update it soon.

**Comment by npduoc** [comment]
@jkasten2 I have just debug it on release mode. Unfortunately, the notifications work to be ok today. Therefore, I do not have any logcat.

**Comment by jkasten2** [comment]
@npduoc Thanks for the update, the stack trace doesn't include any OneSignal classes so OneSignal isn't the direct cause of the crash. OneSignal will resume the Activity which means it may fire an `Intent` to your app. I recommend reviewing your code in your `onNewIntent` in your `MainActivity.java` file, ensure you it can handle any cases where the `Intent` is `null` or doesn't contain the data you're expecting. Feel free to share you code, someone maybe able to help to confirm if it is correct here.

**Comment by npduoc** [comment]
Thanks for your support.
