### ISSUE TITLE
Invalid AppId hangs on some fuctions

### ISSUE THREAD

**Issue by mzdm** [OneSignal/OneSignal-Flutter-SDK#574]
Version:  `onesignal_flutter: ^3.3.2`

Some methods can hang forever if you set not existent `AppId`. There are some native errors printed, but I think it should not completely stop the code flow?

Code sample:

```dart
await OneSignal.shared.setAppId('abcd'); // not existent AppId, but flow code flow still continues
await OneSignal.shared.removeExternalUserId(); // but here it hangs for forever
print('Hello'); // this does not get printed
```

Native error:
```
E/OneSignal(14436): OneSignal AppId format is invalid.
E/OneSignal(14436): Example: 'b2f7f966-d8cc-11e4-bed1-df8f05be55ba'
E/OneSignal(14436): 
E/OneSignal(14436): java.lang.IllegalArgumentException: Invalid UUID string: abcd
E/OneSignal(14436): 	at java.util.UUID.fromString(UUID.java:194)
E/OneSignal(14436): 	at com.onesignal.OSUtils.initializationChecker(OSUtils.java:118)
E/OneSignal(14436): 	at com.onesignal.OneSignal.init(OneSignal.java:834)
E/OneSignal(14436): 	at com.onesignal.OneSignal.setAppId(OneSignal.java:728)
E/OneSignal(14436): 	at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1174)
E/OneSignal(14436): 	at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:882)
E/OneSignal(14436): 	at com.onesignal.OneSignal$7.complete(OneSignal.java:1115)
E/OneSignal(14436): 	at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:211)
E/OneSignal(14436): 	at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
E/OneSignal(14436): 	at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:156)
E/OneSignal(14436): 	at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:279)
E/OneSignal(14436): 	at java.lang.Thread.run(Thread.java:919)
```

**Comment by jkasten2** [comment]
@mzdm Thanks for pointing this out. The intended behavior is to await on methods like `removeExternalUserId`, `sendTag`, etc until there is an id set. In this case it is invalid as your example shows, we could throw in the SDK but this would be a breaking change for this version. We will consider this in a future major release if it is an API design decision that could better handle this case.
