### ISSUE TITLE
[Bug]: App crashes when launched (Android 13)

### ISSUE THREAD

**Issue by Holofox** [OneSignal/OneSignal-Flutter-SDK#604]
### What happened?

The latest SDK is causing a crash on Android 13 on Google Pixel devices.

<details>
  <summary>Devices</summary>
  
| Google Pixel 5A  | Google Pixel 6 |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/19191492/196137178-f20e4c0e-6b24-448e-8e24-596395a2eeb8.png)  | ![image](https://user-images.githubusercontent.com/19191492/196137270-a197c182-1a24-4fe9-9a64-5415ff424175.png)  |
  
</details>

### Steps to reproduce?

```Markdown
1. Install v3.4.1 of dependency.
2. Launch the app on Android device.
```

### What did you expect to happen?

I expected the app to open.

### OneSignal Flutter SDK version

3.4.1

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
2022-10-17 13:44:36.780 30777-30777/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example, PID: 30777
    java.lang.ExceptionInInitializerError
        at f.p.d3.D1(OneSignal.java:1)
        at com.onesignal.flutter.OneSignalPlugin.H(OneSignalPlugin.java:2)
        at com.onesignal.flutter.OneSignalPlugin.onMethodCall(OneSignalPlugin.java:16)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:2)
        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:2)
        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:2)
        at io.flutter.embedding.engine.dart.DartMessenger.a(Unknown Source:0)
        at k.b.a.b.b.c.run(Unknown Source:12)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
        at com.onesignal.OSUtils.o(OSUtils.java:1)
        at f.p.m0.<clinit>(NotificationPermissionController.kt:4)
        at f.p.d3.D1(OneSignal.java:1) 
        at com.onesignal.flutter.OneSignalPlugin.H(OneSignalPlugin.java:2) 
        at com.onesignal.flutter.OneSignalPlugin.onMethodCall(OneSignalPlugin.java:16) 
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:2) 
        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:2) 
        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:2) 
        at io.flutter.embedding.engine.dart.DartMessenger.a(Unknown Source:0) 
        at k.b.a.b.b.c.run(Unknown Source:12) 
        at android.os.Handler.handleCallback(Handler.java:942) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7872) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Holofox** [comment]
See also: https://github.com/OneSignal/OneSignal-Android-SDK/issues/1664

**Comment by Holofox** [comment]
The application crashes if you call methods during initialization in the following sequence:

```dart
OneSignal.shared.setLogLevel(config.logLevel, config.visualLevel);
OneSignal.shared.promptUserForPushNotificationPermission(fallbackToSettings: true);
OneSignal.shared.setAppId(config.appId);
```

Method calls must be clearly in this order to solve the problem:

```dart
OneSignal.shared.setLogLevel(config.logLevel, config.visualLevel);
OneSignal.shared.setAppId(config.appId);
OneSignal.shared.promptUserForPushNotificationPermission(fallbackToSettings: true);
```

**Comment by ThangPh96** [comment]
> 

It worked for me, thanks
