### ISSUE TITLE
[Bug]:  Unable to register externalUserId

### ISSUE THREAD

**Issue by Zfinix** [OneSignal/OneSignal-Flutter-SDK#656]
### What happened?

With no change on our Onesignal Implementation player id's stopped registering external user ids on our production application.

### Steps to reproduce?

```Markdown
This happens on `onesignal_flutter: ^3.5.0`, try calling
 ` await OneSignal.shared.setExternalUserId('${loginModel.data.id}');`
```

### What did you expect to happen?

Onesignal External id should be linked to player Ids

### OneSignal Flutter SDK version

3.5.0

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
Non-fatal Exception: FlutterError
PlatformException(0, The operation couldn’t be completed. (com.onesignal.externalUserId error 0.), null, null)

Non-fatal Exception: FlutterError
0  ???                            0x0 StandardMethodCodec.decodeEnvelope + 653 (message_codecs.dart:653)
1  ???                            0x0 MethodChannel._invokeMethod + 315 (platform_channel.dart:315)
2  ???                            0x0 OneSignal.setExternalUserId + 395 (onesignal_flutter.dart:395)
3  ???                            0x0 NotificationService.integrateDevice + 158 (notification_service.dart:158)


..........
[  +18 ms] flutter: ----------------FIREBASE CRASHLYTICS----------------
[   +1 ms] flutter: PlatformException(0, The operation couldn’t be completed. (com.onesignal.externalUserId error 0.), null,
null)
[        ] flutter: 
[        ] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
[        ] #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
[        ] <asynchronous suspension>
[        ] #2      OneSignal.setExternalUserId (package:onesignal_flutter/onesignal_flutter.dart:395:9)
[        ] <asynchronous suspension>
[        ] #3      NotificationService.integrateDevice (package:eden_garden/core/services/notification_service.dart:156:5)
[        ] <asynchronous suspension>

.......... 

Non-fatal Exception: FlutterError
PlatformException(0, The operation couldn’t be completed. (com.onesignal.email error 0.), null, null)

Non-fatal Exception: FlutterError
0  ???                            0x0 StandardMethodCodec.decodeEnvelope + 653 (message_codecs.dart:653)
1  ???                            0x0 MethodChannel._invokeMethod + 315 (platform_channel.dart:315)
2  ???                            0x0 OneSignal.setEmail + 361 (onesignal_flutter.dart:361)
3  ???                            0x0 NotificationService.integrateDevice + 155 (notification_service.dart:155)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zfinix** [comment]
i've figured out the error now closing this:



```
{
ERROR: External Id authentication (auth token) is set to REQUIRED for this application. Please provide an auth token from your backend server or change the setting in the OneSignal dashboard.
VERBOSE: Set external user id Failure with error: Error Domain=com.onesignal.externalUserId Code=0 "(null)" UserInfo={error=External User Id authentication (auth token) is set to REQUIRED for this application. Please provide an auth token from your backend server or change the setting in the OneSignal dashboard.}

```
