### ISSUE TITLE
 Onesignal 5.0.0 dont ask for permission on Release

### ISSUE THREAD

**Issue by Janosoft** [OneSignal/OneSignal-Flutter-SDK#725]
### What happened?

OneSignal.Notifications.requestPermission(true);

In 'debug' mode, a screen requesting user permissions to receive notifications appears, and everything works okay. However, in 'release' mode, nothing happens, causing the app not to subscribe to OneSignal and not be able to receive notifications.
i'm using a fisical phone with Android 13 (fresh installed)

### Steps to reproduce?

```Markdown
Build apk
Install the App
Launch the App
Touch on 'Prompt for Push Permission'
No permission is requested.
The app will not suscribe to OneSignal
No notifications will be recibed
```

### What did you expect to happen?

Expected to get the permission request screen

### OneSignal Flutter SDK version

onesignal_flutter 5.0.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zia-Ch** [comment]
Facing the same issue

**Comment by ranahyder87** [comment]
I'm getting this issue on the emulator too.
At fresh install, it asks for permission but not on the second time.
OneSignal.Notifications.permission value is also false if I run the app a second time on the emulator.
Is there any solution?

**Comment by jonyoung123** [comment]
I'm also facing same issue as above.

**Comment by Zia-Ch** [comment]
@gdeglin @leemunroe @nicolasvan I know you guys are busy in heavy tasks building great tools for the community. But please have a look into this issue as latest release for flutter is not working at all.  When a new user opens the app, it does not ask for notification permissions, and also not adding him into audiences(in One Signal Dashboard). Please have a closer look why its happening. It worked while debugging but failed to work once app is published.

**Comment by jmcculloch** [comment]
Same. Found this in logcat:
```
--------- beginning of main
2023-09-07 09:40:14.840  1292-1363  flutter                 pid-1292                             E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#initialize on channel OneSignal)
                                                                                                    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308)
                                                                                                    <asynchronous suspension>
2023-09-07 09:40:14.840  1292-1363  flutter                 pid-1292                             E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#lifecycleInit on channel OneSignal#inappmessages)
                                                                                                    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      OneSignalInAppMessages.lifecycleInit (package:onesignal_flutter/src/inappmessages.dart:77)
                                                                                                    <asynchronous suspension>
2023-09-07 09:40:14.841  1292-1363  flutter                 pid-1292                             E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#pushSubscriptionToken on channel OneSignal#pushsubscription)
                                                                                                    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      OneSignalPushSubscription.lifecycleInit (package:onesignal_flutter/src/pushsubscription.dart:65)
                                                                                                    <asynchronous suspension>
2023-09-07 09:40:14.841  1292-1363  flutter                 pid-1292                             E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#permission on channel OneSignal#notifications)
                                                                                                    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      OneSignalNotifications.lifecycleInit (package:onesignal_flutter/src/notifications.dart:121)
                                                                                                    <asynchronous suspension>
2023-09-07 09:40:14.841  1292-1363  flutter                 pid-1292                             E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#requestPermission on channel OneSignal#notifications)
                                                                                                    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      OneSignalNotifications.requestPermission (package:onesignal_flutter/src/notifications.dart:91)
                                                                                                    <asynchronous suspension>
                                                                                                    ```

**Comment by jmcculloch** [comment]
https://stackoverflow.com/questions/65872226/missingpluginexception-in-flutter-in-release-mode-android

This seems to resolve the issue although I'm not sure it's a viable solution to disable resource shrinking/minification at the application level. This seems to be a common problem with flutter->android plugins, looking for a better resolution at the plugin level.

**Comment by nan-li** [comment]
Hi all and thank you @jmcculloch for finding it may be related to shrinking and minification.

If setting this in `build.gradle` resolves the issue for everyone, then we know all of these reports here are the same problem.
```
buildTypes {
    release {
        shrinkResources false
        minifyEnabled false
        signingConfig signingConfigs.release
    }
}
```

We are updating our proguard rules so that the OneSignal SDK can work appropriately after app shrinking and minification. I will update here.

**Comment by Janosoft** [comment]
1. open /app/build.gradle
2. search and add the lines
_buildTypes {
   release {
    //ADD HERE THIS TWO LINES
            shrinkResources false
            minifyEnabled false
 }
}_
3. save
4. run flutter build apk NOW IT WORKS
5. Wait until Onesignal to solve it. Thanks @nan-li 👾❤️

PD: I keeped the **signingConfig signingConfigs.debug** because i dont have any signingConfig yet

**Comment by alectogeek** [comment]
Ooookay, rolling back the package version....

**Comment by MaximilianFlechtner** [comment]
+1

**Comment by graux** [comment]
+1 
This is taking too long to fix!

**Comment by jmcculloch** [comment]
> +1 This is taking too long to fix!

https://github.com/OneSignal/OneSignal-Flutter-SDK/releases 5.0.1

**Comment by Janosoft** [comment]
I just tested removing the workaround 
shrinkResources false
minifyEnabled false
in the app/build.gradle

and now it works!
🤗❤️ Thanks, i'm clossing the issue

**Comment by MAlazhariy** [comment]
I faced the same issue in both (release and debug modes), and I got this error:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#requestPermission on channel OneSignal#notifications)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      OneSignalNotifications.requestPermission (package:onesignal_flutter/src/notifications.dart:88:12)
```
----

### So the solution for me was to ensure to initialize the app before `requestPermission`

```dart
  // initialize first
  OneSignal.initialize(appId);
  // then request the notification permission
  OneSignal.Notifications.requestPermission(true);
```
