### ISSUE TITLE
OneSignal Flutter v5.0.1 not working

### ISSUE THREAD

**Issue by akanxa** [OneSignal/OneSignal-Flutter-SDK#742]
### How can we help?

In this major version release of OneSignal SDK, the message goes through successfully, but in the OneSignal account, it displays a failed status, and the message is not getting delivered.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @akanxa,

Failed delivery can be caused by a few different issues:
1. Your OneSignal Application Settings are incorrect.
2. These tokens belong to an app that does not match your OneSignal settings.
3. A backend error occurred.
4. The FCM sender id on Android or the Bundle ID on iOS have changed from what these devices originally subscribed under.

We need more information to understand the issue.

- Can you give more information about your reproduction steps? 
- What is the Android device and version? 
- Does it happen across all devices? 
- Did this device upgrade from a previous version of the OneSignal Flutter SDK?
- Does this issue happen after a new app install?
- What leads you to think it is related to Firebase?

**Comment by giovanni256** [comment]
Same here while migrating from v3

1) OneSignal is initialized, then I get some errors:

```
E/MethodChannel#OneSignal( 5100): Failed to handle method call
E/MethodChannel#OneSignal( 5100): java.lang.IllegalArgumentException: Expected receiver of type com.amazon.device.iap.internal.d, but got kotlin.Unit
E/MethodChannel#OneSignal( 5100): 	at java.lang.reflect.Field.get(Native Method)
E/MethodChannel#OneSignal( 5100): 	at com.onesignal.core.internal.purchases.impl.TrackAmazonPurchase.start(TrackAmazonPurchase.kt:83)
E/MethodChannel#OneSignal( 5100): 	at com.onesignal.core.internal.startup.StartupService.start(StartupService.kt:16)
E/MethodChannel#OneSignal( 5100): 	at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:247)
E/MethodChannel#OneSignal( 5100): 	at com.onesignal.OneSignal.initWithContext(OneSignal.kt:126)
E/MethodChannel#OneSignal( 5100): 	at com.onesignal.flutter.OneSignalPlugin.initWithContext(OneSignalPlugin.java:128)
E/MethodChannel#OneSignal( 5100): 	at com.onesignal.flutter.OneSignalPlugin.onMethodCall(OneSignalPlugin.java:111)
E/MethodChannel#OneSignal( 5100): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#OneSignal( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#OneSignal( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#OneSignal( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#OneSignal( 5100): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#OneSignal( 5100): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#OneSignal( 5100): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#OneSignal( 5100): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#OneSignal( 5100): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/MethodChannel#OneSignal( 5100): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#OneSignal( 5100): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#OneSignal( 5100): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/DartMessenger( 5100): Uncaught exception in binary message listener
E/DartMessenger( 5100): java.lang.Exception: Must call 'initWithContext' before use
E/DartMessenger( 5100): 	at com.onesignal.internal.OneSignalImp.getInAppMessages(OneSignalImp.kt:83)
E/DartMessenger( 5100): 	at com.onesignal.OneSignal.getInAppMessages(OneSignal.kt:78)
E/DartMessenger( 5100): 	at com.onesignal.flutter.OneSignalInAppMessages.lifecycleInit(OneSignalInAppMessages.java:90)
E/DartMessenger( 5100): 	at com.onesignal.flutter.OneSignalInAppMessages.onMethodCall(OneSignalInAppMessages.java:52)
E/DartMessenger( 5100): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/DartMessenger( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/DartMessenger( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger( 5100): 	at android.os.Handler.handleCallback(Handler.java:942)
E/DartMessenger( 5100): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger( 5100): 	at android.os.Looper.loopOnce(Looper.java:201)
E/DartMessenger( 5100): 	at android.os.Looper.loop(Looper.java:288)
E/DartMessenger( 5100): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/DartMessenger( 5100): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger( 5100): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/DartMessenger( 5100): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/DartMessenger( 5100): Uncaught exception in binary message listener
E/DartMessenger( 5100): java.lang.Exception: Must call 'initWithContext' before use
E/DartMessenger( 5100): 	at com.onesignal.internal.OneSignalImp.getUser(OneSignalImp.kt:84)
E/DartMessenger( 5100): 	at com.onesignal.OneSignal.getUser(OneSignal.kt:46)
E/DartMessenger( 5100): 	at com.onesignal.flutter.OneSignalPushSubscription.onMethodCall(OneSignalPushSubscription.java:45)
E/DartMessenger( 5100): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/DartMessenger( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/DartMessenger( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger( 5100): 	at android.os.Handler.handleCallback(Handler.java:942)
E/DartMessenger( 5100): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger( 5100): 	at android.os.Looper.loopOnce(Looper.java:201)
E/DartMessenger( 5100): 	at android.os.Looper.loop(Looper.java:288)
E/DartMessenger( 5100): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/DartMessenger( 5100): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger( 5100): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/DartMessenger( 5100): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/DartMessenger( 5100): Uncaught exception in binary message listener
E/DartMessenger( 5100): java.lang.Exception: Must call 'initWithContext' before use
E/DartMessenger( 5100): 	at com.onesignal.internal.OneSignalImp.getNotifications(OneSignalImp.kt:81)
E/DartMessenger( 5100): 	at com.onesignal.OneSignal.getNotifications(OneSignal.kt:62)
E/DartMessenger( 5100): 	at com.onesignal.flutter.OneSignalNotifications.onMethodCall(OneSignalNotifications.java:54)
E/DartMessenger( 5100): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/DartMessenger( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/DartMessenger( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger( 5100): 	at android.os.Handler.handleCallback(Handler.java:942)
E/DartMessenger( 5100): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger( 5100): 	at android.os.Looper.loopOnce(Looper.java:201)
E/DartMessenger( 5100): 	at android.os.Looper.loop(Looper.java:288)
E/DartMessenger( 5100): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/DartMessenger( 5100): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger( 5100): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/DartMessenger( 5100): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
D/TrafficStats( 5100): tagSocket(139) with statsTag=0x2710, statsUid=-1
D/TrafficStats( 5100): tagSocket(138) with statsTag=0x2710, statsUid=-1
W/Parcel  ( 5100): Expecting binder but got null!
I/flutter ( 5100): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 5100): PlatformException(error, Expected receiver of type com.amazon.device.iap.internal.d, but got kotlin.Unit, null, java.lang.IllegalArgumentException: Expected receiver of type com.amazon.device.iap.internal.d, but got kotlin.Unit
I/flutter ( 5100): 	at java.lang.reflect.Field.get(Native Method)
I/flutter ( 5100): 	at com.onesignal.core.internal.purchases.impl.TrackAmazonPurchase.start(TrackAmazonPurchase.kt:83)
I/flutter ( 5100): 	at com.onesignal.core.internal.startup.StartupService.start(StartupService.kt:16)
I/flutter ( 5100): 	at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:247)
I/flutter ( 5100): 	at com.onesignal.OneSignal.initWithContext(OneSignal.kt:126)
I/flutter ( 5100): 	at com.onesignal.flutter.OneSignalPlugin.initWithContext(OneSignalPlugin.java:128)
I/flutter ( 5100): 	at com.onesignal.flutter.OneSignalPlugin.onMethodCall(OneSignalPlugin.java:111)
I/flutter ( 5100): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
I/flutter ( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter ( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMes
I/flutter ( 5100): #0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:652
I/flutter ( 5100): #1      MethodChannel._invokeMethod
platform_channel.dart:310
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): ----------------------------------------------------
I/flutter ( 5100): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 5100): MissingPluginException(No implementation found for method OneSignal#lifecycleInit on channel OneSignal#inappmessages)
I/flutter ( 5100): #0      MethodChannel._invokeMethod
platform_channel.dart:308
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): #1      OneSignalInAppMessages.lifecycleInit
inappmessages.dart:77
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): ----------------------------------------------------
I/flutter ( 5100): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 5100): MissingPluginException(No implementation found for method OneSignal#pushSubscriptionToken on channel OneSignal#pushsubscription)
I/flutter ( 5100): #0      MethodChannel._invokeMethod
platform_channel.dart:308
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): #1      OneSignalPushSubscription.lifecycleInit
pushsubscription.dart:65
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): ----------------------------------------------------
I/flutter ( 5100): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 5100): MissingPluginException(No implementation found for method OneSignal#permission on channel OneSignal#notifications)
I/flutter ( 5100): #0      MethodChannel._invokeMethod
platform_channel.dart:308
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): #1      OneSignalNotifications.lifecycleInit
notifications.dart:121
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): ----------------------------------------------------
E/OneSignal( 5100): Must call 'initWithContext' before using Login
E/DartMessenger( 5100): Uncaught exception in binary message listener
E/DartMessenger( 5100): java.lang.Exception: Must call 'initWithContext' before use
E/DartMessenger( 5100): 	at com.onesignal.internal.OneSignalImp.getUser(OneSignalImp.kt:84)
E/DartMessenger( 5100): 	at com.onesignal.OneSignal.getUser(OneSignal.kt:46)
E/DartMessenger( 5100): 	at com.onesignal.flutter.OneSignalUser.addEmail(OneSignalUser.java:84)
E/DartMessenger( 5100): 	at com.onesignal.flutter.OneSignalUser.onMethodCall(OneSignalUser.java:40)
E/DartMessenger( 5100): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/DartMessenger( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/DartMessenger( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger( 5100): 	at android.os.Handler.handleCallback(Handler.java:942)
E/DartMessenger( 5100): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger( 5100): 	at android.os.Looper.loopOnce(Looper.java:201)
E/DartMessenger( 5100): 	at android.os.Looper.loop(Looper.java:288)
E/DartMessenger( 5100): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/DartMessenger( 5100): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger( 5100): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/DartMessenger( 5100): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/DartMessenger( 5100): Uncaught exception in binary message listener
E/DartMessenger( 5100): java.lang.Exception: Must call 'initWithContext' before use
E/DartMessenger( 5100): 	at com.onesignal.internal.OneSignalImp.getUser(OneSignalImp.kt:84)
E/DartMessenger( 5100): 	at com.onesignal.OneSignal.getUser(OneSignal.kt:46)
E/DartMessenger( 5100): 	at com.onesignal.flutter.OneSignalUser.removeTags(OneSignalUser.java:116)
E/DartMessenger( 5100): 	at com.onesignal.flutter.OneSignalUser.onMethodCall(OneSignalUser.java:50)
E/DartMessenger( 5100): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/DartMessenger( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/DartMessenger( 5100): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger( 5100): 	at android.os.Handler.handleCallback(Handler.java:942)
E/DartMessenger( 5100): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger( 5100): 	at android.os.Looper.loopOnce(Looper.java:201)
E/DartMessenger( 5100): 	at android.os.Looper.loop(Looper.java:288)
E/DartMessenger( 5100): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/DartMessenger( 5100): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger( 5100): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/DartMessenger( 5100): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/DartMessenger( 5100): Uncaught exception in binary message listener
E/DartMessenger( 5100): java.lang.Exception: Must call 'initWithContext' before use
E/DartMessenger( 5100): 	at com.onesignal.internal.OneSignalImp.getUser(OneSignalImp.kt:84)
E/DartMessenger( 5100): 	at com.onesignal.OneSignal.getUser(OneSignal.kt:46)
E/DartMessenger( 5100): 	at com.onesignal.flutter.OneSignalUser.removeTags(OneSignalUser.java:116)
E/DartMessenger( 5100): 	at com.onesignal.flutter.OneSignalUser.onMethodCall(OneSignalUser.java:50)
E/DartMessenger( 5100): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
I/flutter ( 5100): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 5100): MissingPluginException(No implementation found for method OneSignal#addEmail on channel OneSignal#user)
I/flutter ( 5100): #0      MethodChannel._invokeMethod
platform_channel.dart:308
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): #1      OneSignalUser.addEmail
user.dart:82
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): ----------------------------------------------------
I/flutter ( 5100): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 5100): MissingPluginException(No implementation found for method OneSignal#removeTags on channel OneSignal#user)
I/flutter ( 5100): #0      MethodChannel._invokeMethod
platform_channel.dart:308
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): #1      OneSignalUser.removeTags
user.dart:77
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): ----------------------------------------------------
I/flutter ( 5100): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 5100): MissingPluginException(No implementation found for method OneSignal#removeTags on channel OneSignal#user)
I/flutter ( 5100): #0      MethodChannel._invokeMethod
platform_channel.dart:308
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): #1      OneSignalUser.removeTags
user.dart:77
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): #2      OneSignalUser.removeTag
user.dart:72
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): ----------------------------------------------------
I/flutter ( 5100): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 5100): MissingPluginException(No implementation found for method OneSignal#removeTags on channel OneSignal#user)
I/flutter ( 5100): #0      MethodChannel._invokeMethod
platform_channel.dart:308
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): #1      OneSignalUser.removeTags
user.dart:77
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): #2      OneSignalUser.removeTag
user.dart:72
I/flutter ( 5100): <asynchronous suspension>
I/flutter ( 5100): ----------------------------------------------------
```

2) Emulator and a real device (Oppo Find X3) with Android 13

3) Yes, it happens on all devices

4) Yes, this happens when upgrading from v3

**Comment by akanxa** [comment]
> Hi @akanxa,
> 
> Failed delivery can be caused by a few different issues:
> 
> 1. Your OneSignal Application Settings are incorrect.
> 2. These tokens belong to an app that does not match your OneSignal settings.
> 3. A backend error occurred.
> 4. The FCM sender id on Android or the Bundle ID on iOS have changed from what these devices originally subscribed under.
> 
> We need more information to understand the issue.
> 
> * Can you give more information about your reproduction steps?
> * What is the Android device and version?
> * Does it happen across all devices?
> * Did this device upgrade from a previous version of the OneSignal Flutter SDK?
> * Does this issue happen after a new app install?
> * What leads you to think it is related to Firebase?



> Hi @akanxa,
> 
> Failed delivery can be caused by a few different issues:
> 
> 1. Your OneSignal Application Settings are incorrect.
> 2. These tokens belong to an app that does not match your OneSignal settings.
> 3. A backend error occurred.
> 4. The FCM sender id on Android or the Bundle ID on iOS have changed from what these devices originally subscribed under.
> 
> We need more information to understand the issue.
> 
> * Can you give more information about your reproduction steps?
> * What is the Android device and version?
> * Does it happen across all devices?
> * Did this device upgrade from a previous version of the OneSignal Flutter SDK?
> * Does this issue happen after a new app install?
> * What leads you to think it is related to Firebase?

I have already checked the onesignal account setting. This issue occurs after updating to the latest version. In the v3.5.1 version, it works properly but after updating the version the message is sent successfully but a failed status is received on onesignal account. Also If I send a message directly through one signal account then also it works.

**Comment by ThakarRajesh** [comment]
Hi there,
I experience the same problem. Anybody discover the answer, @nan-li? Please respond to us as soon as possible. OneSignal often releases updates containing bugs. developer pain at OneSignal.

**Comment by emawby** [comment]
@giovanni256 Your issue seems to be an issue with initialization which is different from the original issue in the thread. Could you please create a separate issue so that yours doesn't get lost!

**Comment by ThakarRajesh** [comment]
Hello @nan-li @emawby  Any update? 
Notification is occasionally received and occasionally not.  We are anxiously awaiting the current situation. Please provide us with a quick fix for that.
Due to this notification issue, many of our users are lost. Are you going to fix this problem?

**Comment by nan-li** [comment]
Hi @akanxa 

> ... the message is sent successfully through API but a failed status is received on the onesignal account. Also If I send a message directly through one signal account then also it works.

I want to make sure I understand completely. When you send a notification via the REST API with the [Create Notification endpoint](https://documentation.onesignal.com/reference/create-notification), you see a failed status in the [OneSignal dashboard ](dashboard.onesignal.com)and no notification is received by your device?

But if you send the notification through the OneSignal dashboard, the notification sends successfully to your device? 

If so, there may be an issue with the request you are making via the REST API. What is the response when you use the API?

**Comment by nan-li** [comment]
Hi @ThakarRajesh,

> Notification is occasionally received and occasionally not.

The issue you have is notifications are not consistently received by a device? 

Can you share more details? If you can be more **specific**, that will be very helpful. Are you using the OneSignal dashboard or sending via the REST API?

- Can you give more information about your reproduction steps? 
- What is the Android device and version? 
- Does it happen across all devices? 
- Did this device upgrade from a previous version of the OneSignal Flutter SDK?
- Does this issue happen after a new app install?

**Comment by phuchuynhStrong** [comment]
I got the same problem and got it working by kept OneSignal classes while minifying. Add this line to your Proguard
`-keep class com.onesignal.** { *; }`

**Comment by nan-li** [comment]
Hi @phuchuynhStrong,

To clarify, you also ran into notifications failing and not being delivered?
And you fixed that with your Proguard update `-keep class com.onesignal.** { *; }`?

**Comment by phuchuynhStrong** [comment]
Hi @nan-li,

Yes. I got into a situation where I couldn't receive notification with release builds

**Comment by nan-li** [comment]
Closing due to no response from my two recent posts asking for more information.
