### ISSUE TITLE
API not returning anything for awhile

### ISSUE THREAD

**Issue by uj** [OneSignal/OneSignal-Flutter-SDK#79]
**Description:**
OneSignal is taking a really long time (3 minutes or more) to subscribe a user and return a UserID, even with the github example.  It keeps showing UserID=null.  This was working before today, byt then today it was having this issue in my own app, so I used the github exmaple to make sure it wasn't an issue with my app.  I'm using the github example exactly, no modifications, with the only change being that I replace the example appid with my own appid. 

Network is working fine on the phone, I can browse websites, I can browse the onesignal.com website.

**Environment**
Android 8.1

Here is the log as the example runs:

```
Launching lib\main.dart on Moto G 5 Plus in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device Moto G 5 Plus...
D/SharedPreferencesImpl(30224): Time required to fsync /data/user/0/com.onesignal.onesignalexample/shared_prefs/OneSignal.xml: [<1: 0, <2: 0, <4: 0, <8: 0, <16: 0, <32: 0, <64: 0, <128: 0, <256: 0, <512: 1, <1024: 0, <2048: 0, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]
I/flutter (30224): Setting consent to true
I/flutter (30224): Setting state
I/OneSignal(30224): Restoring notifications
E/ActivityThread(30224): Failed to find provider info for com.teslacoilsw.notifier
D/OneSignal(30224): registerUser: registerForPushFired:false, locationFired: true, awlFired: false
D/OneSignal(30224): Starting request to get Android parameters.
D/OneSignal(30224): OneSignalRestClient: Making request to: https://onesignal.com/api/v1/apps/********-****-****-****-************/android_params.js
D/NetworkSecurityConfig(30224): No Network Security Config specified, using platform default
I/OneSignal(30224): Querying DB for notifs to restore: created_time > 1554573036 AND dismissed = 0 AND opened = 0 AND is_summary = 0
I/flutter (30224): SUBSCRIPTION STATE CHANGED: {
I/flutter (30224):   "from": "{
I/flutter (30224):   "subscribed": false,
I/flutter (30224):   "userSubscriptionSetting": false,
I/flutter (30224):   "pushToken": null,
I/flutter (30224):   "userId": null
I/flutter (30224): }",
I/flutter (30224):   "to": "{
I/flutter (30224):   "subscribed": false,
I/flutter (30224):   "userSubscriptionSetting": true,
I/flutter (30224):   "pushToken": null,
I/flutter (30224):   "userId": null
I/flutter (30224): }"
I/flutter (30224): }

```

 About 3 minutes later  I get this:

```
W/OneSignal(30224): OneSignalRestClient: null Error thrown from network stack. 
W/OneSignal(30224): java.io.InterruptedIOException: thread interrupted
W/OneSignal(30224): 	at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
W/OneSignal(30224): 	at com.android.okhttp.okio.Okio$1.write(Okio.java:73)
W/OneSignal(30224): 	at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
W/OneSignal(30224): 	at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
W/OneSignal(30224): 	at com.android.okhttp.internal.http.Http1xStream.finishRequest(Http1xStream.java:161)
W/OneSignal(30224): 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:735)
W/OneSignal(30224): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
W/OneSignal(30224): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
W/OneSignal(30224): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
W/OneSignal(30224): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
W/OneSignal(30224): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
W/OneSignal(30224): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
W/OneSignal(30224): 	at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:150)
W/OneSignal(30224): 	at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:38)
W/OneSignal(30224): 	at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:98)
W/OneSignal(30224): 	at java.lang.Thread.run(Thread.java:764)
I/OneSignal(30224): Failed to get Android parameters, trying again in 30 seconds.

```

30 seconds later, it registers properly.  It does this every time I reinstall it.

**Comment by uj** [comment]
Also, I can open the Internet browser, browse to 
https://onesignal.com/api/v1/apps/********-****-****-****-************/android_params.js
and it returns a pageful of json data, every time.  The internet browser never ever times out with that link, only the app does.

**Comment by uj** [comment]
Ok, so I found that if I disable IPv6 in my router, OneSignal works fine.  If I enable IPv6 in my router, OneSignal never works for the first 3 mininutes.  I don't know if it falls back to IPv4 when it retries, or why it works after it retries.  I can browse websites fine with IPv6, both the IPv4 and IP46 version of websites.  My Internet connection passes all of the IPv6 tests like https://test-ipv6.com/ and https://ipv6test.google.com/

So, at least that answers that for now, but any idea why this is happening?

**Comment by rgomezp** [comment]
Hello,
It's not really clear what is happening. It could be the device that is having issues.

**Comment by rgomezp** [comment]
Closing due to no response
