### ISSUE TITLE
App crashes on notification receive when app is closed

### ISSUE THREAD

**Issue by Galahand** [OneSignal/OneSignal-Flutter-SDK#8]
Everytime i get a notification on android when the app is closed the device displays that the app is crashed and i get the following logs:

```
08-14 15:56:13.753 12918-12918/? W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 SPD:SEPF_SECMOBILE_7.0_0006 RAM:SEPF_SECMOBILE_7.0_0009, [-1 -1 -9 -1 0 1]
08-14 15:56:13.756 12918-12918/? I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.pitahaya.milagritoapp 
08-14 15:56:13.762 12918-12918/? I/art: Late-enabling -Xcheck:jni
08-14 15:56:13.793 12918-12918/? D/TimaKeyStoreProvider: TimaSignature is unavailable
08-14 15:56:13.794 12918-12918/? D/ActivityThread: Added TimaKeyStore provider
08-14 15:56:13.846 12918-12918/com.pitahaya.milagritoapp D/ContextRelationMgrBrdg: loadKlass() : caller=com.samsung.android.bridge.multiscreen.common.ContextRelationManagerBridge.<clinit>:28 android.app.LoadedApk.makeApplication:840 
08-14 15:56:13.881 12918-12918/com.pitahaya.milagritoapp I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.RemoteMessage>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbgl;
08-14 15:56:13.882 12918-12918/com.pitahaya.milagritoapp I/art:     at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
        at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:400)
        at java.lang.Class java.lang.Class.forName(java.lang.String) (Class.java:326)
        at boolean com.google.firebase.iid.FirebaseInstanceId.zzm() ((null):-1)
        at boolean com.google.firebase.iid.FirebaseInstanceId.zzl() ((null):-1)
        at void com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase.FirebaseApp, com.google.firebase.iid.zzah) ((null):-1)
        at void com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase.FirebaseApp) ((null):-1)
        at java.lang.Object com.google.firebase.iid.zzai.create(com.google.firebase.components.ComponentContainer) ((null):-1)
        at java.lang.Object com.google.firebase.components.zzh.zza(com.google.firebase.components.ComponentFactory, com.google.firebase.components.ComponentContainer) (SourceFile:28)
        at java.lang.Object com.google.firebase.components.zzi.get() ((null):-1)
        at java.lang.Object com.google.firebase.components.zzh.get() (SourceFile:39)
        at java.lang.Object com.google.firebase.components.ComponentContainer$$CC.get(com.google.firebase.components.ComponentContainer, java.lang.Class) ((null):15)
        at java.lang.Object com.google.firebase.components.zzd.get(java.lang.Class) (SourceFile:-1)
        at void com.google.firebase.components.zzd.zza(boolean) (SourceFile:68)
        at void com.google.firebase.FirebaseApp.zze() (SourceFile:703)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions, java.lang.String) (SourceFile:328)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions) (SourceFile:294)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context) (SourceFile:281)
        at boolean com.google.firebase.provider.FirebaseInitProvider.onCreate() (SourceFile:37)
        at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo, boolean) (ContentProvider.java:1758)
        at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (ContentProvider.java:1733)
        at void com.google.firebase.provider.FirebaseInitProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (SourceFile:31)
        at android.app.IActivityManager$ContentProviderHolder android.app.ActivityThread.installProvider(android.content.Context, android.app.IActivityManager$ContentProviderHolder, android.content.pm.ProviderInfo, boolean, boolean, boolean) (ActivityThread.java:6335)
        at void android.app.ActivityThread.installContentProviders(android.content.Context, java.util.List) (ActivityThread.java:5927)
        at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5866)
        at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1703)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
        at void android.os.Looper.loop() (Looper.java:154)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6692)
        at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1468)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1358)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbgl" on path: DexPathList[[zip file "/data/app/com.pitahaya.milagritoapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.pitahaya.milagritoapp-1/lib/arm64, /data/app/com.pitahaya.milagritoapp-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
        at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:400)
        at java.lang.Class java.lang.Class.forName(java.lang.String) (Class.java:326)
        at boolean com.google.firebase.iid.FirebaseInstanceId.zzm() ((null):-1)
        at boolean com.google.firebase.iid.FirebaseInstanceId.zzl() ((null):-1)
        at void com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase.FirebaseApp, com.google.firebase.iid.zzah) ((null):-1)
        at void com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase.FirebaseApp) ((null):-1)
        at java.lang.Object com.google.firebase.iid.zzai.create(com.google.firebase.components.ComponentContainer) ((null):-1)
        at java.lang.Object com.google.firebase.components.zzh.zza(com.google.firebase.components.ComponentFactory, com.google.firebase.components.ComponentContainer) (SourceFile:28)
        at java.lang.Object com.google.firebase.components.zzi.get() ((null):-1)
        at java.lang.Object com.google.firebase.components.zzh.get() (SourceFile:39)
        at java.lang.Object com.google.firebase.components.ComponentContainer$$CC.get(com.google.firebase.components.ComponentContainer, java.lang.Class) ((null):15)
        at java.lang.Object com.google.firebase.components.zzd.get(java.lang.Class) (SourceFile:-1)
        at void com.google.firebase.components.zzd.zza(boolean) (SourceFile:68)
        at void com.google.firebase.FirebaseApp.zze() (SourceFile:703)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions, java.lang.String) (SourceFile:328)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions) (SourceFile:294)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context) (SourceFile:281)
        at boolean com.google.firebase.provider.FirebaseInitProvider.onCreate() (SourceFile:37)
        at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo, boolean) (ContentProvider.java:1758)
        at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (ContentProvider.java:1733)
        at void com.google.firebase.provider.FirebaseInitProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (SourceFile:31)
        at android.app.IActivityManager$ContentProviderHolder android.app.ActivityThread.installProvider(android.content.Context, android.app.IActivityManager$ContentProviderHolder, android.content.pm.ProviderInfo, boolean, boolean, boolean) (ActivityThread.java:6335)
        at void android.app.ActivityThread.installContentProviders(android.content.Context, java.util.List) (ActivityThread.java:5927)
        at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5866)
        at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1703)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
        at void android.os.Looper.loop() (Looper.java:154)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6692)
        at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1468)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1358)
08-14 15:56:13.892 12918-12918/com.pitahaya.milagritoapp V/FA: Registered activity lifecycle callback
08-14 15:56:13.894 12918-12918/com.pitahaya.milagritoapp D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
08-14 15:56:13.894 12918-12918/com.pitahaya.milagritoapp I/FirebaseInitProvider: FirebaseApp initialization successful
08-14 15:56:13.921 12918-12945/com.pitahaya.milagritoapp D/NetworkSecurityConfig: No Network Security Config specified, using platform default
08-14 15:56:13.931 12918-12945/com.pitahaya.milagritoapp I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
    (HTTPLog)-Static: isSBSettingEnabled false
08-14 15:56:13.980 12918-12944/com.pitahaya.milagritoapp V/FA: Collection enabled
08-14 15:56:13.981 12918-12944/com.pitahaya.milagritoapp V/FA: App package, google app id: com.pitahaya.milagritoapp, 1:531101699633:android:c6c75387021e40ec
08-14 15:56:13.983 12918-12944/com.pitahaya.milagritoapp I/FA: App measurement is starting up, version: 12780
    To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
08-14 15:56:13.984 12918-12944/com.pitahaya.milagritoapp I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.pitahaya.milagritoapp
08-14 15:56:13.984 12918-12944/com.pitahaya.milagritoapp D/FA: Debug-level message logging enabled
08-14 15:56:14.063 12918-12944/com.pitahaya.milagritoapp V/FA: Connecting to remote service
08-14 15:56:14.090 12918-12944/com.pitahaya.milagritoapp V/FA: Connection attempt already in progress
08-14 15:56:14.194 12918-12918/com.pitahaya.milagritoapp I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.RemoteMessage>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbgl;
        at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
        at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:400)
        at java.lang.Class java.lang.Class.forName(java.lang.String) (Class.java:326)
        at boolean com.google.firebase.iid.FirebaseInstanceId.zzm() ((null):-1)
        at boolean com.google.firebase.iid.FirebaseInstanceId.zzl() ((null):-1)
        at void com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase.FirebaseApp, com.google.firebase.iid.zzah) ((null):-1)
08-14 15:56:14.195 12918-12918/com.pitahaya.milagritoapp I/art:     at void com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase.FirebaseApp) ((null):-1)
        at java.lang.Object com.google.firebase.iid.zzai.create(com.google.firebase.components.ComponentContainer) ((null):-1)
        at java.lang.Object com.google.firebase.components.zzh.zza(com.google.firebase.components.ComponentFactory, com.google.firebase.components.ComponentContainer) (SourceFile:28)
        at java.lang.Object com.google.firebase.components.zzi.get() ((null):-1)
        at java.lang.Object com.google.firebase.components.zzh.get() (SourceFile:39)
        at java.lang.Object com.google.firebase.components.ComponentContainer$$CC.get(com.google.firebase.components.ComponentContainer, java.lang.Class) ((null):15)
        at java.lang.Object com.google.firebase.components.zzd.get(java.lang.Class) (SourceFile:-1)
        at void com.google.firebase.components.zzd.zza(boolean) (SourceFile:68)
        at void com.google.firebase.FirebaseApp.zze() (SourceFile:703)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions, java.lang.String) (SourceFile:328)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions) (SourceFile:294)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context) (SourceFile:281)
        at boolean com.google.firebase.provider.FirebaseInitProvider.onCreate() (SourceFile:37)
        at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo, boolean) (ContentProvider.java:1758)
        at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (ContentProvider.java:1733)
        at void com.google.firebase.provider.FirebaseInitProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (SourceFile:31)
        at android.app.IActivityManager$ContentProviderHolder android.app.ActivityThread.installProvider(android.content.Context, android.app.IActivityManager$ContentProviderHolder, android.content.pm.ProviderInfo, boolean, boolean, boolean) (ActivityThread.java:6335)
        at void android.app.ActivityThread.installContentProviders(android.content.Context, java.util.List) (ActivityThread.java:5927)
        at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5866)
        at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1703)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
        at void android.os.Looper.loop() (Looper.java:154)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6692)
        at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1468)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1358)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbgl" on path: DexPathList[[zip file "/data/app/com.pitahaya.milagritoapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.pitahaya.milagritoapp-1/lib/arm64, /data/app/com.pitahaya.milagritoapp-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
        at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:400)
        at java.lang.Class java.lang.Class.forName(java.lang.String) (Class.java:326)
        at boolean com.google.firebase.iid.FirebaseInstanceId.zzm() ((null):-1)
        at boolean com.google.firebase.iid.FirebaseInstanceId.zzl() ((null):-1)
        at void com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase.FirebaseApp, com.google.firebase.iid.zzah) ((null):-1)
        at void com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase.FirebaseApp) ((null):-1)
        at java.lang.Object com.google.firebase.iid.zzai.create(com.google.firebase.components.ComponentContainer) ((null):-1)
        at java.lang.Object com.google.firebase.components.zzh.zza(com.google.firebase.components.ComponentFactory, com.google.firebase.components.ComponentContainer) (SourceFile:28)
        at java.lang.Object com.google.firebase.components.zzi.get() ((null):-1)
        at java.lang.Object com.google.firebase.components.zzh.get() (SourceFile:39)
        at java.lang.Object com.google.firebase.components.ComponentContainer$$CC.get(com.google.firebase.components.ComponentContainer, java.lang.Class) ((null):15)
        at java.lang.Object com.google.firebase.components.zzd.get(java.lang.Class) (SourceFile:-1)
        at void com.google.firebase.components.zzd.zza(boolean) (SourceFile:68)
        at void com.google.firebase.FirebaseApp.zze() (SourceFile:703)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions, java.lang.String) (SourceFile:328)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions) (SourceFile:294)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context) (SourceFile:281)
        at boolean com.google.firebase.provider.FirebaseInitProvider.onCreate() (SourceFile:37)
        at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo, boolean) (ContentProvider.java:1758)
        at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (ContentProvider.java:1733)
        at void com.google.firebase.provider.FirebaseInitProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (SourceFile:31)
        at android.app.IActivityManager$ContentProviderHolder android.app.ActivityThread.installProvider(android.content.Context, android.app.IActivityManager$ContentProviderHolder, android.content.pm.ProviderInfo, boolean, boolean, boolean) (ActivityThread.java:6335)
        at void android.app.ActivityThread.installContentProviders(android.content.Context, java.util.List) (ActivityThread.java:5927)
        at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5866)
        at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1703)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
        at void android.os.Looper.loop() (Looper.java:154)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6692)
        at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1468)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1358)
08-14 15:56:14.205 12918-12918/com.pitahaya.milagritoapp I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.RemoteMessage>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbgl;
        at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
        at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:400)
        at java.lang.Class java.lang.Class.forName(java.lang.String) (Class.java:326)
        at boolean com.google.firebase.iid.FirebaseInstanceId.zzm() ((null):-1)
        at boolean com.google.firebase.iid.FirebaseInstanceId.zzl() ((null):-1)
        at void com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase.FirebaseApp, com.google.firebase.iid.zzah) ((null):-1)
        at void com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase.FirebaseApp) ((null):-1)
        at java.lang.Object com.google.firebase.iid.zzai.create(com.google.firebase.components.ComponentContainer) ((null):-1)
        at java.lang.Object com.google.firebase.components.zzh.zza(com.google.firebase.components.ComponentFactory, com.google.firebase.components.ComponentContainer) (SourceFile:28)
        at java.lang.Object com.google.firebase.components.zzi.get() ((null):-1)
        at java.lang.Object com.google.firebase.components.zzh.get() (SourceFile:39)
        at java.lang.Object com.google.firebase.components.ComponentContainer$$CC.get(com.google.firebase.components.ComponentContainer, java.lang.Class) ((null):15)
        at java.lang.Object com.google.firebase.components.zzd.get(java.lang.Class) (SourceFile:-1)
        at void com.google.firebase.components.zzd.zza(boolean) (SourceFile:68)
        at void com.google.firebase.FirebaseApp.zze() (SourceFile:703)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions, java.lang.String) (SourceFile:328)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions) (SourceFile:294)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context) (SourceFile:281)
        at boolean com.google.firebase.provider.FirebaseInitProvider.onCreate() (SourceFile:37)
        at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo, boolean) (ContentProvider.java:1758)
        at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (ContentProvider.java:1733)
        at void com.google.firebase.provider.FirebaseInitProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (SourceFile:31)
        at android.app.IActivityManager$ContentProviderHolder android.app.ActivityThread.installProvider(android.content.Context, android.app.IActivityManager$ContentProviderHolder, android.content.pm.ProviderInfo, boolean, boolean, boolean) (ActivityThread.java:6335)
        at void android.app.ActivityThread.installContentProviders(android.content.Context, java.util.List) (ActivityThread.java:5927)
        at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5866)
        at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1703)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
        at void android.os.Looper.loop() (Looper.java:154)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6692)
        at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1468)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1358)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbgl" on path: DexPathList[[zip file "/data/app/com.pitahaya.milagritoapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.pitahaya.milagritoapp-1/lib/arm64, /data/app/com.pitahaya.milagritoapp-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
        at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:400)
        at java.lang.Class java.lang.Class.forName(java.lang.String) (Class.java:326)
        at boolean com.google.firebase.iid.FirebaseInstanceId.zzm() ((null):-1)
        at boolean com.google.firebase.iid.FirebaseInstanceId.zzl() ((null):-1)
        at void com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase.FirebaseApp, com.google.firebase.iid.zzah) ((null):-1)
        at void com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase.FirebaseApp) ((null):-1)
        at java.lang.Object com.google.firebase.iid.zzai.create(com.google.firebase.components.ComponentContainer) ((null):-1)
        at java.lang.Object com.google.firebase.components.zzh.zza(com.google.firebase.components.ComponentFactory, com.google.firebase.components.ComponentContainer) (SourceFile:28)
        at java.lang.Object com.google.firebase.components.zzi.get() ((null):-1)
        at java.lang.Object com.google.firebase.components.zzh.get() (SourceFile:39)
        at java.lang.Object com.google.firebase.components.ComponentContainer$$CC.get(com.google.firebase.components.ComponentContainer, java.lang.Class) ((null):15)
        at java.lang.Object com.google.firebase.components.zzd.get(java.lang.Class) (SourceFile:-1)
        at void com.google.firebase.components.zzd.zza(boolean) (SourceFile:68)
        at void com.google.firebase.FirebaseApp.zze() (SourceFile:703)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions, java.lang.String) (SourceFile:328)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions) (SourceFile:294)
        at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context) (SourceFile:281)
        at boolean com.google.firebase.provider.FirebaseInitProvider.onCreate() (SourceFile:37)
        at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo, boolean) (ContentProvider.java:1758)
        at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (ContentProvider.java:1733)
        at void com.google.firebase.provider.FirebaseInitProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (SourceFile:31)
        at android.app.IActivityManager$ContentProviderHolder android.app.ActivityThread.installProvider(android.content.Context, android.app.IActivityManager$ContentProviderHolder, android.content.pm.ProviderInfo, boolean, boolean, boolean) (ActivityThread.java:6335)
        at void android.app.ActivityThread.installContentProviders(android.content.Context, java.util.List) (ActivityThread.java:5927)
        at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5866)
        at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1703)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
        at void android.os.Looper.loop() (Looper.java:154)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6692)
        at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1468)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1358)
08-14 15:56:14.210 12918-12962/com.pitahaya.milagritoapp E/AndroidRuntime: FATAL EXCEPTION: Firebase-FirebaseMessagingService
    Process: com.pitahaya.milagritoapp, PID: 12918
    java.lang.AbstractMethodError: abstract method "void com.google.firebase.iid.zzb.zzd(android.content.Intent)"
        at com.google.firebase.iid.zzc.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:762)
```
i'm using these plugins:
```
  cupertino_icons: ^0.1.0
  flutter_facebook_login: ^1.1.0
  url_launcher: ^3.0.0
  firebase_auth: ^0.5.18
  firebase_storage: ^1.0.1
  cloud_firestore: ^0.7.4
  qr_flutter: ^1.1.1
  intl: ^0.15.4
  transparent_image: ^0.1.0
  shared_preferences: ^0.4.2
  location: 1.2.0
  onesignal: 1.0.1
```
and have these dependencies in my app.gradle
```
dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation "com.google.android.gms:play-services-location:15.0.1"
    implementation 'com.android.support:multidex:1.0.3'
}
apply plugin: 'com.google.gms.google-services'
```

**Comment by Nightsd01** [comment]
Hi, if anyone else sees a similar error, please post on here and I'll reopen the issue and help investigate.

If anyone does see this issue again please add the following code to the VERY top of your `app/build.gradle` and let me know if it fixes your issue, it's our gradle plugin that automatically aligns dependencies in Android:

```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.11.0, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
    maven { url 'https://maven.google.com' }
}
```

**Comment by daniel-van-niekerk** [comment]
I also had to add that bit above app/build.gradle, otherwise the app just crashes immediately when it launches.
