### ISSUE TITLE
[Bug]: App is unrsponsive on android due to main (blocked)

### ISSUE THREAD

**Issue by vamsi-kleargroup** [OneSignal/OneSignal-Flutter-SDK#838]
### What happened?

We are experiencing crash/deadlock on some of our android phones 

### Steps to reproduce?

```Markdown
1. Installed onesignal_flutter: ^5.0.4
2. Initialize onesignal
3. OneSignal.Debug.setLogLevel(OSLogLevel.verbose);
4. OneSignal.initialize("appid");
5. await OneSignal.login(user.id!);
```

### What did you expect to happen?

I expect the app to run as expected without getting stuck 

### OneSignal Flutter SDK version

5.0.4

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
main (blocked):tid=1 systid=16282 | waiting to lock <0x00dfacbd> (java.util.Collections$SynchronizedMap) held by thread 75
       at com.onesignal.common.r.g.setOptAnyProperty(unavailable:12)
       at com.onesignal.common.r.g.setOptBooleanProperty(unavailable:10)
       at com.onesignal.common.r.g.setOptBooleanProperty$default(unavailable:13)
       at com.onesignal.core.d.d.a.setConsentGiven(unavailable:9)
       at f.k.f.a.setConsentGiven(unavailable:15)
       at f.k.d.o(unavailable:6)
       at com.onesignal.flutter.f.l(unavailable:12)
       at com.onesignal.flutter.f.onMethodCall(unavailable:38)
       at j.a.d.a.j$a.a(unavailable:17)
       at io.flutter.embedding.engine.h.e.k(unavailable:18)
       at io.flutter.embedding.engine.h.e.l(unavailable:40)
       at io.flutter.embedding.engine.h.e.m(unavailable)
       at io.flutter.embedding.engine.h.a.run(unavailable:12)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8918)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @vamsi-kleargroup, 

Thanks for reporting, we made fixes to Android to resolve deadlocks and was released in [Release 5.1.0](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.0). Please upgrade your dependency!
