### ISSUE TITLE
[Bug]: OneSignal.login PlatformException(error, null, null, java.lang.NullPointerException

### ISSUE THREAD

**Issue by burakcbdn** [OneSignal/OneSignal-Flutter-SDK#846]
### What happened?

After upgrading to the latest version, our app records errors from OneSignal.login method, here is the full error.

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, null, null, java.lang.NullPointerException
	at com.onesignal.internal.OneSignalImp.login(OneSignalImp.kt:313)
	at com.onesignal.IOneSignal$DefaultImpls.login(IOneSignal.kt:117)
	at com.onesignal.internal.OneSignalImp.login(OneSignalImp.kt:52)
	at com.onesignal.OneSignal.login(OneSignal.kt:157)
	at com.onesignal.flutter.OneSignalPlugin.login(OneSignalPlugin.java:145)
	at com.onesignal.flutter.OneSignalPlugin.onMethodCall(OneSignalPlugin.java:117)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Steps to reproduce?

```Markdown
1. Install version 5.1.0
2. Call OneSignal.login(userID)
```

### What did you expect to happen?

It should login the user without any error.

### OneSignal Flutter SDK version

Release 5.1.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @burakcbdn,

This is indicating that a `null` external ID is being passed into the `login` method.
Can you confirm that the `userID` you are passing into call `OneSignal.login(userID)` is non-null?
