### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#getPermissionSubscriptionState

### ISSUE THREAD

**Issue by newbieflutter** [OneSignal/OneSignal-Flutter-SDK#87]
I have the following settings for my one signal. My app run and till here it stop with this error message. I have added this OneSignal.shared.getPermissionSubscriptionState(); but still I keep getting the message. So how to resolve this issue ? 

```
2019-05-12 01:05:45.749459+0800 Runner[395:20622] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#getPermissionSubscriptionState on channel OneSignal)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      OneSignal.getPermissionSubscriptionState (package:onesignal/onesignal.dart:209:24)
<asynchronous suspension>
```

```
Future<void> initPlatformState() async {
    
    if (!mounted) return;
    print("Before set log");
    //OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none);
    print("Before set user privacy");
    //OneSignal.shared.setRequiresUserPrivacyConsent(_requireConsent);

    var settings = {
      OSiOSSettings.autoPrompt: false,
      OSiOSSettings.promptBeforeOpeningPushUrl: true
    };
    
    OneSignal.shared.setNotificationReceivedHandler((notification) {
    
      
    });
    
    OneSignal.shared
        .setNotificationOpenedHandler((OSNotificationOpenedResult result) {
      print("Payload only is"+result.notification.payload.jsonRepresentation().toString());
     
    });
    
    OneSignal.shared
        .setSubscriptionObserver((OSSubscriptionStateChanges changes) {
      print("SUBSCRIPTION STATE CHANGED: ${changes.jsonRepresentation()}");
    });

    OneSignal.shared.setPermissionObserver((OSPermissionStateChanges changes) {
      print("PERMISSION STATE CHANGED: ${changes.jsonRepresentation()}");
    });

  
    // NOTE: Replace with your own app ID from https://www.onesignal.com
    await OneSignal.shared
        .init("**************", iOSSettings: settings);
   
    OneSignal.shared.consentGranted(true);
    OneSignal.shared
        .setInFocusDisplayType(OSNotificationDisplayType.notification);
    await OneSignal.shared.getPermissionSubscriptionState();
    bool requiresConsent = await OneSignal.shared.requiresUserPrivacyConsent();
    
  }
```

**Comment by newbieflutter** [comment]
Hi,
    Is a very weird issue I copied the same codes again into a new project and the exception error is gone I really dont know how to answer on this. So I will close this then.
