### ISSUE TITLE
[Bug]: MissingPluginException(No implementation found for method OneSignal#addNativeClickListener on channel OneSignal#notifications)

### ISSUE THREAD

**Issue by hardiklakhalani** [OneSignal/OneSignal-Flutter-SDK#947]
### What happened?

Latest version of SDK (^5.2..4) is throwing the following exception:
```
MissingPluginException(No implementation found for method OneSignal#addNativeClickListener on channel OneSignal#notifications)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
I/flutter (17989): <asynchronous suspension>
```

### Steps to reproduce?

```Markdown
1. Install ^5.2.4 for Android Platform
2. Implement the following after initialization:

OneSignal.Notifications.addClickListener((OSNotificationClickEvent result) async {
///
}

Before migration to v5, it was working fine:
`OneSignal.shared.setNotificationOpenedHandler(OSNotificationOpenedResult result) async { }`

3. Run the app in emulator, this error will occure.
```

### What did you expect to happen?

I expected that method to have existed. If that doesn't exist then proper lint/syntax error should have thrown.

### OneSignal Flutter SDK version

Release ^5.2.4

### Flutter SDK version

Stable 3.19.6

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
MissingPluginException(No implementation found for method OneSignal#addNativeClickListener on channel OneSignal#notifications)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
I/flutter (17989): <asynchronous suspension>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hardiklakhalani** [comment]
in v3, it was working fine even before initializing onesignal, now after migrating to v5, it must be **after** initialization.
Closing as resolved, i guess.
