### ISSUE TITLE
App crash on Android when set OSNotificationDisplayType.none

### ISSUE THREAD

**Issue by badlee** [OneSignal/OneSignal-Flutter-SDK#95]
**Description:**

I have cloned example and changed just the `appId` and line 76 from :
```dart
OneSignal.shared
        .setInFocusDisplayType(OSNotificationDisplayType.notification);
```
to :

```dart
OneSignal.shared
        .setInFocusDisplayType(OSNotificationDisplayType.none);
```

When I send a push notification, I got this error

```
FATAL EXCEPTION: OS_PROC_BUNDLE
Process: com.onesignal.onesignalexample, PID: 26127
java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: OS_PROC_BUNDLE
	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:166)
	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
	at com.onesignal.flutter.OneSignalPlugin.notificationReceived(OneSignalPlugin.java:287)
	at com.onesignal.OneSignal.handleNotificationReceived(OneSignal.java:1970)
	at com.onesignal.NotificationBundleProcessor$1.run(NotificationBundleProcessor.java:446)
	at java.lang.Thread.run(Thread.java:831)
```

**Environment**

onesignal : ^1.1.0
flutter sdk : ">=2.1.0 <3.0.0"
Android : 5.1

**Steps to Reproduce Issue:**

1. git clone https://github.com/OneSignal/OneSignal-Flutter-SDK.git
2.  cd OneSignal-Flutter-SDK/example
3.  flutter packages get
4. put your appId in `lib/main.dart` at line 73
5. change `OSNotificationDisplayType.notification` to `OSNotificationDisplayType.none`  in `lib/main.dart` at line 76
6.  flutter run
7.  Attempt to receive a push notification

**Comment by rgomezp** [comment]
Thanks for your patience while we investigate this issue. We will have to reproduce to learn more about what is happening

**Comment by rgomezp** [comment]
Hello @badlee ,
I wasn't able to reproduce the issue. Do you mind posting your entire pubspec yaml file? I wasn't able to get the lock file to update to the version range you included

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by juppdes** [comment]
Same problem here.

Flutter:  v1.7.8+hotfix.3
onesignal: ^1.1.0

FATAL EXCEPTION: OS_PROC_BUNDLE
java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: OS_PROC_BUNDLE
at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:684)
at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:189)
at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
at com.onesignal.flutter.OneSignalPlugin.notificationReceived(OneSignalPlugin.java:287)
at com.onesignal.OneSignal.handleNotificationReceived(OneSignal.java:1970)
at com.onesignal.NotificationBundleProcessor$1.run(NotificationBundleProcessor.java:446)
at java.lang.Thread.run(Thread.java:764)

**Comment by rgomezp** [comment]
@juppdes this is a duplicate of #99
