### ISSUE TITLE
[Bug]: App crashes to due to NoClassDefFoundError on an Android 5.1 device when requesting permissions

### ISSUE THREAD

**Issue by logickoder** [OneSignal/OneSignal-Flutter-SDK#981]
### What happened?

My app crashes when requesting permission on an Android 5.1 device

### Steps to reproduce?

```Markdown
1. Install v5.2.8
2. Launch the app on an android 5 device
3. Wait for one signal to request the required permissions
4. App crashes
```

### What did you expect to happen?

I expected nothing to happen, especially since I think it is just notification permission and that doesn't exist on android 5

### OneSignal Flutter SDK version

5.2.8

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
Fatal Exception: java.lang.NoClassDefFoundError: r6.e
       at com.onesignal.flutter.OneSignalNotifications.requestPermission(OneSignalNotifications.java:1)
       at com.onesignal.flutter.OneSignalNotifications.onMethodCall(OneSignalNotifications.java:1)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:1)
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:1)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:1)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:5911)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @logickoder thanks for reporting, we will investigate a fix.

The code is heavily obfuscated but I think I know what the issue is, probably this line: https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/a222579a7f06e370582af65c5c7aec8db4b5f363/android/src/main/java/com/onesignal/flutter/OneSignalNotifications.java#L87

**Comment by nan-li** [comment]
The workaround is to check the Android version yourself and don't request permission.

**Comment by nan-li** [comment]
Hi @logickoder we shipped this fix in [Release 5.3.0](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.3.0). Please check it out and reach out with any issues.
